### PR TITLE
Draft Boost Control

### PR DESCRIPTION
**Pull request by 960**

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
I see a lot of of unrelated changes with a lot of MAJOR issues, this is unacceptable level of quality.

**Comment by rusefi** [comment]
"#define EFI_INTERNAL_SLOW_ADC_PWM	&PWMD8"?

you must be kidding. I am not paid enough to review this.

**Comment by 960** [comment]
Wait now, I am cleaning away all the generated stuff to step thru this.

#define EFI_INTERNAL_SLOW_ADC_PWM &PWMD8
I have no Idea where this came from

**Pull request closed without merging**
