### PR TITLE
Tooltip and UI updates

### PR DESCRIPTION
**Pull request by mck1117**
thanks to @BeerMoneyMotorsports

### CODE REVIEW

**Comment by rusefillc** [comment]
I love and need my console commands to be documented, how do we not wipe this stuff out?

Worst case we would need to change code generator to have some content not go into TS ui but I need this content not nuked please.

**Comment by mck1117** [comment]
Putting console commands in the tooltips so that Mr. Rusefi can read them is confusing for all users, and maybe useful for one human.

To quote you on Slack:

> as in everything is valid but serves only 1% of the customers

**Comment by rusefillc** [comment]
As of today tooltips are also header code comments. I agree that we shall decouple butcannot just drop comment. Please either keep or decouple but not drop.

**Comment by rusefillc** [comment]
mostly merged to master

**Pull request closed without merging**
