### PR TITLE
Control stepper with dual H-bridges

### PR DESCRIPTION
**Pull request by mck1117**
#1088

### CODE REVIEW

**Comment by rusefi** [comment]
@dron0gus FYI

**Comment by rusefi** [comment]
Poke, how can I help? Would we need 'useHbridges' setting - can I help by adding it into the configuration?

**Comment by mck1117** [comment]
that would be a helpful step - yes

**Comment by rusefi** [comment]
just added useHbridges

**Comment by rusefi** [comment]
This draft is now a month old. Poke?

**Comment by mck1117** [comment]
image
Ooooh, aaaah!

**Comment by mck1117** [comment]
Bench testing looks okay enough, let's merge!

**Pull request merged**
