### PR TITLE
Fixing build

### PR DESCRIPTION
**Pull request by 960**
Fixing build

### CODE REVIEW

**Comment by rusefi** [comment]
What is this? looks like all this is already in rusefi from previous pull request?

**Comment by 960** [comment]
I need this at the end of board configuration.cpp.

void setAdcChannelOverrides(void) {
}

I still dont understand anything of GIT :-(

**Comment by 960** [comment]
I just figured I need to pull before merging again:-)

That's why the other files are there.

I deleted the repo and forked again now.

What next? Should I close this and merge again or do you add the missing lines?

**Comment by rusefi** [comment]
please close this & make a new one

**Pull request closed without merging**
