### PR TITLE
Possibility to switch between fixed pulsewidth or fuel map for cranking

### PR DESCRIPTION
**Pull request by 960**
Was supposed to be running fuel(with the corrections), but cant find it anymore..

Please edit/change if you can..

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by mck1117** [comment]
I'd recommend changing the setting to read
"Fueling source for cranking": "fixed"/"fuel map"
or something like that.

**Comment by 960** [comment]
It needs to generate new config to build/pass tests

**Comment by 960** [comment]
That's a good idea :-)

**Comment by 960** [comment]
Now, I belive it's ready to go :-)

**Comment by rusefi** [comment]
.input merged & gen_config done - please rebase

**Pull request closed without merging**
