### PR TITLE
Update can_dash.cpp add fuel consumption litres per hour ,protocol aim

### PR DESCRIPTION
**Pull request by Vd2617**

### CODE REVIEW

**Comment by Vd2617** [comment]
Add fuel consumption litres per hour for send to dash ,protocol aim

**Comment by rusefillc** [comment]
thank you @Vd2617! are you on rusEFI forum/discord?

**Comment by Vd2617** [comment]
Нет

**Comment by rusefillc** [comment]
> Нет

https://chat.whatsapp.com/Ey4p7DIDoy299AS1h3ejpB

**Pull request merged**
