### PR TITLE
Extend CAN EGT to six channels

### PR DESCRIPTION
**Pull request by LiQuiD04**
Using AEM X Series EGT CAN protocol we can make six channels EGT extension board.

### CODE REVIEW

**Comment by rusefillc** [comment]
@LiQuiD04 very red? I am sure you've tried compiling this locally maybe some changes were not included in commit?

**Comment by LiQuiD04** [comment]
I was compiling using custom board firmware on github actions with DDEFS += -DRAM_UNUSED_SIZE=200. Nothing fancy. Tested it on real board and it works. Looks like on f407-disco config its going out of memory.

**Comment by rusefillc** [comment]
@LiQuiD04 please clarify, are you suggesting I merge red or something else?

**Comment by LiQuiD04** [comment]
For now I need to think why it fails on f407-disco board. Sorry for wasting your time, its my first pull-request.

**Comment by rusefillc** [comment]
Part of the reason could be https://github.com/rusefi/rusefi/commit/172daed512174c0b941c626d0ad2f8d6f852d327

Note that https://github.com/LiQuiD04/rusefi/tree/more_can_egt was red as well, please consider rebasing and giving your fork a chance to finish CI, things could be better with that change above.

**Comment by LiQuiD04** [comment]
Thanks for the info. I'll follow your suggestions.

**Comment by rusefillc** [comment]
Less broken https://github.com/rusefi/rusefi/commit/dcb4f659734d3e99a88387c0cca2533a593b22bd

**Comment by LiQuiD04** [comment]
Now after [dcb4f65](https://github.com/rusefi/rusefi/commit/dcb4f659734d3e99a88387c0cca2533a593b22bd) it passes checks.
Im not sure about HW-CI, Im waiting 3h for for "runner to pick up this job".

**Pull request merged**
