### PR TITLE
dead pwm tester code

### PR DESCRIPTION
**Pull request by mck1117**

### CODE REVIEW

**Comment by rusefillc** [comment]
what are the arguments for removal? looks like a useful toolset to assert scheduler precision?

**Comment by rusefillc** [comment]
@mck1117 ^^^^?

**Comment by mck1117** [comment]
oh hi

This file seems to have been disabled and had no changes since at least January 2015, 7 years ago.

It's not actually representative of what we care about for running an engine, For that - it's best to actually just feed a trigger signal and inspect the resulting injection/ignition timing with a scope.

**Comment by rusefillc** [comment]
my preference is to keep this dead code

**Pull request closed without merging**
