### PR TITLE
remove dangerous pin options from E34 config

### PR DESCRIPTION
**Pull request by mck1117**
no frankenso should have an ignition output on PB5 - this pinout is weiiiird, maybe some custom board somebody made?

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 please spell this out to me

why is spi init/deinit an issue for us?

**Comment by mck1117** [comment]
SPI init/deinit is a bit sketchy because if you do it mid spi transaction, it could leave an external device in an unpredictable state.  Think about what happens if you reset the SD card's pins in the middle of an SPI transaction.

**Comment by mck1117** [comment]
do we know what board this configuration was supposed to be for? It doesn't look like frankenso.

**Comment by rusefillc** [comment]
I am pretty sure that's something custom

**Comment by rusefillc** [comment]
[junit] I 201218 183317.311 [communication executor1] LinkManager - msg,CRITICAL error: Pin "PB5" required by "Coil 1" but is used by "SPI master out" BMW_E34 20201218@source,
    [junit] I 201218 183317.311 [communication executor1] MessagesCentral - postMessage EngineState: CRITICAL error: Pin "PB5" required by "Coil 1" but is used by "SPI master out" BMW_E34 20201218@source

**Comment by mck1117** [comment]
closing in favor of #2127

**Pull request closed without merging**
