### PR TITLE
Add w202 canDash support

### PR DESCRIPTION
**Pull request by shadowm60**
added CanDash support for w202

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by shadowm60** [comment]
I think it can be closed, if i find something more in the dbc while developing the car i will create a new request.

**Comment by rusefi** [comment]
Usually we do not even need to create a ticket if we plan to PR the complete solution right awau

**Comment by mck1117** [comment]
ooh, more dashboards!

**Pull request merged**
