### PR TITLE
update h7 clock config

### PR DESCRIPTION
**Pull request by mck1117**
progress on #2322, still untested, pending soldering a real chip to a real board

### CODE REVIEW

**Comment by rusefillc** [comment]
400 or 480?

**Comment by mck1117** [comment]
this is the ST drama with increasing the allowed clock speed on the revision V chips - later chips can run at 480, very early ones can only do 400.

What does the actual chip on yours look like? The `V` means it can do 480.

image

**Comment by rusefillc** [comment]
my old nucleo has Y not V

**Comment by mck1117** [comment]
ugh, looks like chibios doesn't even support putting the core regulator in to the correct mode for 480mhz operation, so 400mhz it is.

**Comment by rusefillc** [comment]
image

master: no blinking no USB serial on nucleo-h743zi with "y"

**Comment by mck1117** [comment]
try again, the core is now running at 400

**Comment by rusefillc** [comment]
#2389 created

**Comment by mck1117** [comment]
oh, your board probably has a 25MHz crystal, not 8mhz, so it's trying to run 3.1x too fast

**Comment by mck1117** [comment]
nvm, it is indeed 8MHz on your board

**Comment by mck1117** [comment]
debugging on a real h7 now...

**Comment by mck1117** [comment]
now tested on an H743 - USB enumerates! :tada: :tada: :tada:

**Pull request merged**
