### PR TITLE
Missing CHPRINTF_USE_FLOAT in simulator's chconf.h

### PR DESCRIPTION
**Pull request by fpoussin**
That should one of the simulator bug (#379)

### CODE REVIEW

**Comment by rusefi** [comment]
@fpoussin sorry for a random question: firmware and unit_test Makefiles allow incremental compilation, but win32 functional unit test always wants to do full compilation. Any chance you know what this could be about?

testing simulator now

**Comment by fpoussin** [comment]
I was also wondering that myself, it's probably something in rules.mk
I'll have a look.

**Comment by rusefi** [comment]
@fpoussin I've merged master into chibios branch and this (?) has broken the ff.c again.

I honestly do not get it :( thank you for you patience with me.

**Comment by rusefi** [comment]
I give up :(

I believe I have reverted master merge commit, but still ff.c issues. I have no idea what's going on.

**Comment by fpoussin** [comment]
Try to do a rebase instead of a merge.
I'll have a look.

**Comment by rusefi** [comment]
at the moment I am failing to get it to any working state, need help fixing & explaining my mistake.

**Comment by fpoussin** [comment]
Let's talk about this on slack

**Pull request merged**
