### PR TITLE
fix BACKUP_FLASH_ADDR assertion semantic

### PR DESCRIPTION
**Pull request by nmschulte**
for https://github.com/rusefi/rusefi/pull/4738#issuecomment-1306111813

### CODE REVIEW

**Comment by mck1117** [comment]
should we just be comparing against 0? Or is this actually a pointer? (ie, do we ever dereference `BACKUP_FLASH_ADDR` as a pointer?)

**Comment by rusefillc** [comment]
@mck1117 this all started with gcc11 detecting suspicious/illegal memcpy operations probably around intFlashRead/intFlashWrite

**Comment by mck1117** [comment]
> @mck1117 this all started with gcc11 detecting suspicious/illegal memcpy operations probably around intFlashRead/intFlashWrite

I'm aware of that. I'm asking what the _right_ thing to do is, instead of casting a pointer type to an integer for a comparison (which is a code smell at best)

**Comment by nmschulte** [comment]
`BACKUP_FLASH_ADDR` is typically (except for a `...Write) cast as `flashaddr_t`, which is a `uintptr_t`, so I opted for this than to use `NULL`

**Comment by mck1117** [comment]
I would be in favor of making `flashaddr_t` a pointer type, instead of an integer type. We're using it as a pointer (cast to char* right before the memcpy...)

**Comment by mck1117** [comment]
`uintptr_t` is not a pointer - it's an integer type guaranteed to be at least as large as the pointers on your architecture. Used when you need to store a pointer as an integer instead of a pointer.

**Comment by nmschulte** [comment]
Ah I see.  My C++ is rusty.  Is `uint32_t *` appropriate then?

**Pull request merged**
