### PR TITLE
macOS test debug

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
I tried on my fork and it succeeded. I have no idea why.

### CODE REVIEW

**Comment by chuckwagoncomputing** [comment]
My run for comparison: https://github.com/chuckwagoncomputing/rusefi/actions/runs/8822828017/job/24221888004
The location of realpath is different - `/bin/realpath` on yours and `/usr/local/bin/realpath` on mine. I have no idea why.

**Comment by chuckwagoncomputing** [comment]
Oh mine's on macOS 12.7.4, and your's is on 14.4.1. But WHY? They're both calling for `macos-latest`!

**Comment by rusefillc** [comment]
I have a failing PR askng for macos 13, sounds like i shall be asking for 12?

**Comment by chuckwagoncomputing** [comment]
It seems that `/bin/realpath` is an Apple-included version of realpath starting in macOS 13 that doesn't support all the options. Maybe we should change the alias check to always use grealpath if it exists.

**Pull request closed without merging**
