### PR TITLE
ADC: internalIndex should be used as getAvgAdcValue argument

### PR DESCRIPTION
**Pull request by dron0gus**
-plus output messages re-formated

### CODE REVIEW

**Comment by rusefillc** [comment]
please help me understand if thats a bug. a refactoring or an improvement

**Comment by dron0gus** [comment]
@rusefillc fix of https://github.com/rusefi/rusefi/issues/2617, plus a bit of debug output refactoring.

Force-pushed with build fixed.

**Comment by mck1117** [comment]
can you refactor to use `efiPrintf` instead of a `Logging` object while you're at it?

**Comment by dron0gus** [comment]
@mck1117 done.

**Pull request merged**
