### PR TITLE
GCC-10 and C++ 2a: supress depricated volatile use errors

### PR DESCRIPTION
**Pull request by dron0gus**
Related to https://github.com/rusefi/rusefi/issues/3644

### CODE REVIEW

**Comment by mck1117** [comment]
Can we just fix the deprecated behavior instead? It's deprecated for a reason.

**Comment by dron0gus** [comment]
Tested with:
`gcc version 9.3.1 20200408 (release) (GNU Arm Embedded Toolchain 9-2020-q2-update)`
and
`gcc version 10.3.1 20210824 (release) (GNU Arm Embedded Toolchain 10.3-2021.10)`

**Comment by dron0gus** [comment]
> Can we just fix the deprecated behavior instead? It's deprecated for a reason.

We should not include plain c headers from CMIS to cpp files.
```
In file included from ChibiOS/os/common/ext/ARM/CMSIS/Core/Include/core_cm4.h:1960,
                 from ChibiOS/os/common/ext/ST/STM32F4xx/stm32f407xx.h:183,
                 from ChibiOS/os/common/ext/ST/STM32F4xx/stm32f4xx.h:151,
                 from ChibiOS/os/common/startup/ARMCMx/devices/STM32F4xx/cmparams.h:79,
                 from ChibiOS/os/common/ports/ARMCMx/chcore.h:70,
                 from ChibiOS/os/rt/include/ch.h:111,
                 from ChibiOS/os/hal/osal/rt-nil/osal.h:32,
                 from ChibiOS/os/hal/include/hal.h:28,
                 from ./global.h:15,
                 from ./pch/pch.h:24:
ChibiOS/os/common/ext/ARM/CMSIS/Core/Include/mpu_armv7.h: In function 'void ARM_MPU_Enable(uint32_t)':
ChibiOS/os/common/ext/ARM/CMSIS/Core/Include/mpu_armv7.h:194:14: error: compound assignment with 'volatile'-qualified left operand is deprecated [-Werror=volatile]
  194 |   SCB->SHCSR |= SCB_SHCSR_MEMFAULTENA_Msk;
```

**Comment by dron0gus** [comment]
It is deprecated in C++. C on embedded platform is impossible with such limitations.

**Comment by mck1117** [comment]
Agh, that's annoying.

**Pull request merged**
