### PR TITLE
does gcc11 know something?

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by rusefillc** [comment]
@nmschulte any chance you would be available to PR the fix? need smarter conditional compilation here

**Comment by rusefillc** [comment]
@nmschulte no I mean fix legit compilation erro specifically with cypress configuration, see red checkmark on github compilation status

**Comment by nmschulte** [comment]
I'll see what I can do.

**Comment by nmschulte** [comment]
FWIW, I cannot get even `master` to build w/ `PROJECT_BOARD=cypress PROJECT_CPU=cypress`, complaining about `EFI_FILE_LOGGING` in `ChibiOS/os/various/fatfs_bindings/fatfs_diskio.c`:

```
ChibiOS/os/various/fatfs_bindings/fatfs_diskio.c:30:2: error: #error "MMC_SPI or SDC driver must be specified"
   30 | #error "MMC_SPI or SDC driver must be specified"
      |  ^~~~~
```

I'm very new to the project so missing a lot of context.  I'm not using the `setup_linux_environment.sh` or any other configuration-like mechanisms, just running `make` -- it seems like this should work but perhaps I'm missing something re: configuration.  I'll analyze the Jenkins/CI scripts, and also try the version of GCC referenced in `setup_linux_environment.sh`, or anything else you direct me to.

**Comment by mck1117** [comment]
cypress and kinetis are "weird" - try running their compile scripts instead of just bare `make`

**Comment by nmschulte** [comment]
> cypress and kinetis are "weird" - try running their compile scripts instead of just bare `make`

That resolved things (`export USE_FATFS="no", etc.), thanks; I'm able to reproduce the issue.  Is this "weird"ness intentional, then?  Seems like the board/cpu could set these "as normal."  Anyway, I'll dig more into the semantic issue later tongiht :+1:.

**Comment by mck1117** [comment]
> Is this "weird"ness intentional, then?

Not really, no. IMO all those settings should get set in the `*.mk` files, not in shell scripts. The makefiles are far, far more portable than the wacky shell script way of doing it. That might be another good one to tackle.

**Pull request merged**
