### PR TITLE
ETB and sent

### PR DESCRIPTION
**Pull request by dron0gus**
At least it start moving...
```
tpsSensor = Sensor.new("Tps1")
tpsSensor : setRedundant(true)
ppsSensor = Sensor.new("AcceleratorPedal")
ppsSensor : setRedundant(true)
cnt = 10
restartEtb()
setTickRate(100)
function onTick()
	cnt = cnt + 1

	sentValue = getSentValue(1)
	tpsValue = interpolate(0.11, 0, 0.89, 100, sentValue)

	tpsSensor : set(tpsValue )
	ppsSensor : set(cnt / 10)
	print('sentValue ' ..sentValue..' tps ' ..tpsValue .. ' pps ' .. (cnt/10))
	if (cnt >= 1000) then
		cnt = 10
	end
end

```

### CODE REVIEW

**Comment by dron0gus** [comment]
Still fails to "Auto Calibrate EBT" couse faked from LUA `Tps1Primary` and `Tps1Secondary` still return zero
```
tpsPrimary = Sensor.new("Tps1Primary")
tpsSecondary = Sensor.new("Tps1Secondary")
--tpsPrimary : setRedundant(true)
--tpsSecondary : setRedundant(true)
tpsSensor = Sensor.new("Tps1")
tpsSensor : setRedundant(true)
ppsSensor = Sensor.new("AcceleratorPedal")
ppsSensor : setRedundant(true)
cnt = 10
restartEtb()
setTickRate(100)
function onTick()
	cnt = cnt + 1

--	sentSig0,sentSig1 = getSentValues(1)
	sentSig0 = getSentValues(1)
	sentSig1 = 0xfff - sentSig0
--	Fake mV
	sentV0 = sentSig0 / 0xfff * 3300
	sentV1 = sentSig1 / 0xfff * 3300
--	print('Sig0 ' ..sentV0.. ' Sig1 ' ..sentV1)
--	print('Sent ' ..getSentValue(1))
	tpsValue = interpolate(0.11, 0, 0.89, 100, sentSig0 / 0xfff)

	tpsSensor : set(tpsValue)
--	Fake mV
	tpsPrimary : set(sentV0)
	tpsSecondary : set(sentV1)
	ppsSensor : set(cnt / 10)
--	print('tps ' ..tpsValue .. ' pps ' .. (cnt/10))
	if (cnt >= 1000) then
		cnt = 10
	end
end
```

**Comment by dron0gus** [comment]
Also:
`sentSig0,sentSig1 = getSentValues(1)`
Expected: returns two values
Actual result: returns one value and nil

**Comment by rusefillc** [comment]
We might want to close this one in light of https://github.com/rusefi/rusefi/issues/4688#issuecomment-1312367020

**Comment by rusefillc** [comment]
From 12 commits here nine are already in master and two should not go into master in my opinion

We only need https://github.com/rusefi/rusefi/pull/4735/commits/c1b02e7c28bbfdb4df2b87b223653a61aec0161a @dron0gus please extract into separate branch or drop from this branch

**Comment by rusefillc** [comment]
Most commits are already in master and a couple of commits are totally not needed


closing

**Pull request closed without merging**
