### PR TITLE
lua pid class

### PR DESCRIPTION
**Pull request by mck1117**
depends on something being done about https://github.com/gengyong/luaaa/issues/7

### CODE REVIEW

**Comment by mck1117** [comment]
this builds/passes tests once we have https://github.com/rusefi/luaaa/pull/4

**Comment by rusefillc** [comment]
is this PR supposed to touch 	branch = rusefi_prod_2019 line in https://github.com/rusefi/rusefi/blob/master/.gitmodules?

**Comment by rusefillc** [comment]
@mck1117 it seems red

**Comment by rusefillc** [comment]
it's a really weird list of failed vs successful checks. what makes those three checks special in terms of lua?

since we are confused I think it's time to split the PR into two pieces - lua version bump is one thing and PID class is another thing

**Comment by mck1117** [comment]
HW CI is out of system lua memory

**Comment by rusefillc** [comment]
let's please get https://github.com/rusefi/rusefi/pull/3434 green before revisiting this one? i.e. let's split these two changes into two PRs

**Review by rusefillc — CHANGES_REQUESTED** [review]
please separate lua update from Pid change

**Pull request merged**
