### PR TITLE
ChibiOS 16.x update

### PR DESCRIPTION
**Pull request by fpoussin**
Let me know if this works, I had to make a lot of changes to the mass storage driver.

You'll need to init and pull the ChibiOS submodule:
_git submodule update --init_

When you are ready to merge the pull request, I will rebase/merge on your master so that you can do it from github.

Because of the CRLF crap, make sure your windows git client it setup as "checkout as CRLF, commit as LF". This should be the default. It's the equivalent of autocrlf.

### CODE REVIEW

**Comment by rusefi** [comment]
Please excuse my luddism, just added https://github.com/rusefi/rusefi/tree/master/firmware/ChibiOS_16 folder under #72 

Next step for me would be to document all patches to existing chibios folder so that we can hopefully implement some of them in a better way.

Thank you for you patience with me!

**Comment by fpoussin** [comment]
I think it's a bad idea to try to keep you own local version of ChibiOS, as later upgrades will be a huge pain instead of one easy command.
Can you make all you changes external to its code base? (using hooks or adding code in the conf files)

**Comment by rusefi** [comment]
@fpoussin you are definitely right, what you propose would the the best but longest route. My suggestion is to split into multiple separate smaller efforts.

I only have that much time to learn new things and improve the approach, hopefully ChibiOS_16 folder would be a good compromise for a short-term solution.

**Comment by fpoussin** [comment]
I think it's more like doubling the effort since you'll have to do it anyways.

I did re-implement most changes while leaving the ChibiOS code base untouched so there's little left to do.
It just needs testing.

What I would call a good compromise is forking ChibiOS, creating you own branch based on the stable one, and applying your patches there. 
When you need to update the OS you just need to rebase the branch and you always know exactly what you changed.

**Comment by rusefi** [comment]
@fpoussin you are forcing me to make a bigger effort than what I can currently afford :(

**Comment by fpoussin** [comment]
I can do that for you.

Delete this repo: https://github.com/rusefi/ChibiOS
Fork this one: https://github.com/ChibiOS/ChibiOS

Give me the admin rights on it, I will create a branch with the patches then I can update my pull request to point to it. If there are some missing things you can add them directly.

**Comment by rusefi** [comment]
delete done
fork done
https://github.com/rusefi/ChibiOS/invitations
not sure if that's admin right yet so far I am trying to add you as collaborator

**Comment by fpoussin** [comment]
I have push rights so that should work :) 
I'll let you know when it's ready.

**Comment by rusefi** [comment]
See also https://github.com/rusefi/rusefi/issues/380

**Comment by fpoussin** [comment]
I think we are good to merge now.
I added the contrib repo for mass storage, there's a bunch of existing drivers you might want to use later on.

You can merge to another branch while doing some testing so that I can rebase my work on it and avoid having to fix line ending for every commit you make. ;)

**Comment by rusefi** [comment]
:(

**Comment by fpoussin** [comment]
I totally understand.
So the easiest way would be to clone my repo, checkout the chibios-update branch and compile+test the code. You can also create another branch here and I can change the pull request to point to it.
The current mass storage driver you are using is not compatible with ChibiOS 3, this one is, other members are using it. Here: https://github.com/ChibiOS/ChibiOS-Contrib/tree/master/testhal/STM32/STM32F7xx/USB_MSD (I am one of the maintainers)

I had to move the board files because they were in the modified ChibiOS. They are exactly the same.
It's huge because of the OEL stuff, otherwise there's not so many changes.

Whatever you decide nothing is permanent and you can always revert changes.

**Comment by rusefi** [comment]
I think we need to start by fixing the EOL mess

I've made some changes to the .gitattributes file but it's still a mess

At the moment if I git clone a clean copy I have a couple of files modified right from the beginning of a clean copy, because of EOL stuff. This makes me really excited :(

**Comment by rusefi** [comment]
Commited my version of #380 and maybe improved .gitattributes and created a branch for your PR https://github.com/rusefi/rusefi/tree/fresh_chibios_by_fpoussin

Do you need to re-point your PR into the new branch or do I need to do something? Can you please resoleve the conflict with my #380 implementation?

**Comment by fpoussin** [comment]
Alright, I'm running some tests with the debugger, I'll let you know when I'm happy with the results.
I'll handle the conflicts no worries.

**Comment by fpoussin** [comment]
2017-03-22 23_18_09-chsys c origin_stable_rusefi - rusefi - qt creator
Running into this now...

**Comment by rusefi** [comment]
unlockanycontext is my method, i believe it uses some flag to decide which branch to use? Probably flag value not right?

**Comment by fpoussin** [comment]
Yeah I'm slowly working through some asserts, already fixed a bunch.
It's mainly caused by variable name changes inside chibios (ie: dbg_isr_cnt > ch.dbg.isr_cnt).

**Comment by fpoussin** [comment]
Okay it runs now :)

**Comment by fpoussin** [comment]
2017-03-23 00_45_58-console 20170314 firmware 20170318 13225 custom 27 com15
It's aliiive! :)

**Comment by rusefi** [comment]
Did i see c:/ as in windows? Does win simulator compile also?

**Comment by fpoussin** [comment]
I haven't tried to work on the simulator, I'll have a look.
I'm using the pre-compiled binaries now.

**Comment by fpoussin** [comment]
So the Win32 simulator does not compile now, I'll check tonight, almost fixed it.

**Comment by fpoussin** [comment]
Can you test the current code and see if everything behaves correctly?

**Comment by rusefi** [comment]
image

failed to build simulator - do I do anything wrong?

**Comment by rusefi** [comment]
Oh I've missed git submodule update --init

Still not a huge fan of one extra command to init a repo clone. Why is not that part of the clone? Any work arounds?

Yes submodules are great yes tracking rusEfi patch of ChibiOS in a separate repo is great but how to reduce the end-user confusion?

**Comment by rusefi** [comment]
Simulator does not link will look more into this

i686-w64-mingw32-
image

**Comment by rusefi** [comment]
ff.c not found even with modules initialized, need your help

image

**Comment by fpoussin** [comment]
It was using the file bundled with chibios, I changed that.

There's no workaround for the git submodules, that's the way it works.
Maybe you can we can add a check somewhere in the makefile (or have it do the submodule init/update when building)

For the simulator, I built it on MSYS2, using the 32bit toolchain, same as you.

**Comment by rusefi** [comment]
I was able to compile the firmware, thank you for the ff.c fix!

I will run RealHwTest.java test suite once I am back at home tonight, hope to run a car this weekend.

What about EOL issues - is it any better with explicit text eol=lf now? I wonder how do we split the EOL resolution from ChibiOS update

**Comment by fpoussin** [comment]
I'll see what I can do.
I'd need to separate removing the old chibios files, the EOL stuff and the code modifications to support 16.x

**Comment by rusefi** [comment]
java test suite failed

Command [reset_engine_chart] executed in 523
Got confirmation in 523ms
java.lang.IllegalStateException: VBatt Expected 12.0 but got 0.1
	at com.rusefi.AutoTest.assertEquals(AutoTest.java:423)
	at com.rusefi.AutoTest.assertEquals(AutoTest.java:418)
	at com.rusefi.AutoTest.test2003DodgeNeon(AutoTest.java:144)
	at com.rusefi.AutoTest.mainTestBody(AutoTest.java:32)
	at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:59)
	at com.rusefi.RealHwTest.main(RealHwTest.java:23)
Waiting for 361 byte(s): output channels body

**Comment by fpoussin** [comment]
I just cleaned and pushed the branch, it's a lot easier to see the changes now.
I'll check the tests.

**Comment by rusefi** [comment]
can we please not delete chibios_16 in this branch? only to make the PR smaller

also 
while compiling simulator "--library-path=,," is casuing an error on linking
/usr/lib/gcc/i686-w64-mingw32/5.4.0/../../../../i686-w64-mingw32/bin/ld: cannot find : No such file or directory
collect2: error: ld returned 1 exit status

**here are some details.**



master, not failed to compile simulator:



i686-w64-mingw32-g++ -c  -c -Wall -O2           -Werror-implicit-function-declaration  -Wno-error=pointer-sign -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=sign-compare -Wno-error=unused-parameter -Wno-error=missing-field-initializers -Wno-error=write-strings -Wno-error=strict-aliasing -ffunction-sections -fdata-sections -fno-common -std=c++11 -fno-rtti -fpermissive -fno-exceptions -fno-use-cxa-atexit -Wall -Wextra -Wa,-alms=build/lst/trigger_emulator.lst   -MD -MP -MF .dep/trigger_emulator.o.d  -I. -I. -I../firmware/chibios/os/ports/GCC/SIMIA32 -I../firmware/chibios/os/kernel/include -I../firmware/chibios/os/hal/include -I../firmware/chibios/os/hal/platforms/Win32 -I../firmware/chibios/boards/simulator -I../firmware/util -I../firmware/console -I../firmware/console/binary -I../firmware/console/fl_binary -I../firmware/config/engines -I../firmware/ext_algo -I../firmware/controllers -I../firmware/hw_layer/algo -I../firmware/development -I../firmware/controllers/algo -I../firmware/controllers/core -I../firmware/controllers/math -I../firmware/controllers/sensors -I../firmware/controllers/system -I../firmware/controllers/trigger -I../firmware/controllers/trigger/decoders -I../firmware/chibios/os/various -Isimulator ../firmware/development/trigger_emulator.cpp -o build/obj/trigger_emulator.o



i686-w64-mingw32-g++ -c  -c -Wall -O2           -Werror-implicit-function-declaration  -Wno-error=pointer-sign -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=sign-compare -Wno-error=unused-parameter -Wno-error=missing-field-initializers -Wno-error=write-strings -Wno-error=strict-aliasing -ffunction-sections -fdata-sections -fno-common -std=c++11 -fno-rtti -fpermissive -fno-exceptions -fno-use-cxa-atexit -Wall -Wextra -Wa,-alms=build/lst/boards.lst   -MD -MP -MF .dep/boards.o.d  -I. -I. -I../firmware/chibios/os/ports/GCC/SIMIA32 -I../firmware/chibios/os/kernel/include -I../firmware/chibios/os/hal/include -I../firmware/chibios/os/hal/platforms/Win32 -I../firmware/chibios/boards/simulator -I../firmware/util -I../firmware/console -I../firmware/console/binary -I../firmware/console/fl_binary -I../firmware/config/engines -I../firmware/ext_algo -I../firmware/controllers -I../firmware/hw_layer/algo -I../firmware/development -I../firmware/controllers/algo -I../firmware/controllers/core -I../firmware/controllers/math -I../firmware/controllers/sensors -I../firmware/controllers/system -I../firmware/controllers/trigger -I../firmware/controllers/trigger/decoders -I../firmware/chibios/os/various -Isimulator simulator/boards.cpp -o build/obj/boards.o



i686-w64-mingw32-g++   build/obj/chcore.o build/obj/chsys.o build/obj/chdebug.o build/obj/chlists.o build/obj/chvt.o build/obj/chschd.o build/obj/chthreads.o build/obj/chdynamic.o build/obj/chregistry.o build/obj/chsem.o build/obj/chmtx.o build/obj/chcond.o build/obj/chevents.o build/obj/chmsg.o build/obj/chmboxes.o build/obj/chqueues.o build/obj/chmemcore.o build/obj/chheap.o build/obj/chmempools.o build/obj/hal.o build/obj/adc.o build/obj/can.o build/obj/ext.o build/obj/gpt.o build/obj/i2c.o build/obj/icu.o build/obj/mac.o build/obj/mmc_spi.o build/obj/mmcsd.o build/obj/pal.o build/obj/pwm.o build/obj/rtc.o build/obj/sdc.o build/obj/serial.o build/obj/serial_usb.o build/obj/spi.o build/obj/tm.o build/obj/uart.o build/obj/usb.o build/obj/hal_lld.o build/obj/pal_lld.o build/obj/serial_lld.o build/obj/map_adjuster.o build/obj/nmea.o build/obj/board.o build/obj/chprintf.o build/obj/memstreams.o build/obj/crc.o build/obj/data_buffer.o build/obj/rfiutil.o build/obj/histogram.o build/obj/main.o  build/obj/cyclic_buffer.o build/obj/datalogging.o build/obj/loggingcentral.o build/obj/listener_array.o build/obj/cli_registry.o build/obj/efilib.o build/obj/efilib2.o build/obj/LocalVersionHolder.o build/obj/advance_map.o build/obj/idle_controller.o build/obj/malfunction_central.o build/obj/auto_generated_enums.o build/obj/fuel_math.o build/obj/accel_enrichment.o build/obj/engine_configuration.o build/obj/engine.o build/obj/lcd_menu_tree.o build/obj/event_registry.o build/obj/algo.o build/obj/aux_pid.o build/obj/signal_executor.o build/obj/settings.o build/obj/engine_controller.o build/obj/error_handling.o build/obj/sensor_chart.o build/obj/trigger_emulator_algo.o build/obj/rpm_calculator.o build/obj/trigger_central.o build/obj/spark_logic.o build/obj/main_trigger_callback.o build/obj/trigger_bmw.o build/obj/trigger_mazda.o build/obj/trigger_chrysler.o build/obj/trigger_structure.o build/obj/trigger_decoder.o build/obj/trigger_simulator.o build/obj/trigger_mitsubishi.o build/obj/trigger_nissan.o build/obj/trigger_subaru.o build/obj/trigger_toyota.o build/obj/trigger_gm.o build/obj/trigger_honda.o build/obj/trigger_rover.o build/obj/trigger_universal.o build/obj/pwm_generator_logic.o build/obj/signal_executor_sleep.o build/obj/event_queue.o build/obj/efiGpio.o build/obj/SingleTimerExecutor.o build/obj/tunerstudio_io.o build/obj/tunerstudio.o build/obj/status_loop.o build/obj/console_io.o build/obj/fl_protocol.o build/obj/eficonsole.o build/obj/thermistors.o build/obj/allsensors.o build/obj/map.o build/obj/voltage.o build/obj/maf.o build/obj/tps.o build/obj/ego.o build/obj/hip9011_lookup.o build/obj/EfiWave.o build/obj/avg_values.o build/obj/table_helper.o build/obj/fsio_core.o build/obj/interpolation.o build/obj/fsio_impl.o build/obj/engine_math.o build/obj/pid.o build/obj/biquad.o build/obj/speed_density.o build/obj/engine_sniffer.o build/obj/ford_aspire.o build/obj/custom_engine.o build/obj/MiniCooperR50.o build/obj/acura_rsx.o build/obj/audi_aan.o build/obj/bmw_e34.o build/obj/mazda_miata.o build/obj/mazda_miata_1_6.o build/obj/mazda_miata_vvt.o build/obj/citroenBerlingoTU3JP.o build/obj/dodge_neon.o build/obj/ford_fiesta.o build/obj/ford_1995_inline_6.o build/obj/nissan_primera.o build/obj/mazda_miata_nb.o build/obj/honda_accord.o build/obj/subaru.o build/obj/snow_blower.o build/obj/GY6_139QMB.o build/obj/rover_v8.o build/obj/mazda_323.o build/obj/mazda_626.o build/obj/saturn_ion.o build/obj/sachs.o build/obj/test_engine.o build/obj/mitsubishi.o build/obj/gm_2_2.o build/obj/dodge_ram.o build/obj/vw.o build/obj/dodge_stratus.o build/obj/chevrolet_camaro_4.o build/obj/suzuki_vitara.o build/obj/daihatsu.o build/obj/chevrolet_c20_1973.o build/obj/toyota_jzs147.o build/obj/lada_kalina.o build/obj/geo_storm.o build/obj/zil130.o build/obj/honda_600.o build/obj/ford_festiva.o build/obj/rusEfiFunctionalTest.o build/obj/framework.o build/obj/map_averaging.o build/obj/trigger_emulator.o build/obj/boards.o   -Wl,-Map=build/rusefi_simulator.map,--cref,--no-warn-mismatch,--gc-sections  -static-libgcc -static-libstdc++ -lws2_32 -lm -o build/rusefi_simulator





failed to compiler simulator in branch:

i686-w64-mingw32-g++ -c  -Os  -ffunction-sections -fdata-sections -fno-common -std=c++11 -fno-rtti -fpermissive -fno-exceptions -fno-use-cxa-atexit -Wall -Wextra -Wa,-alms=build/lst/map_averaging.lst  -DSIMULATOR -MD -MP -MF .dep/map_averaging.o.d -Os  -ffunction-sections -fdata-sections -fno-common -I. -I. -I../firmware/ChibiOS/os/rt/ports/SIMIA32/compilers/GCC -I../firmware/ChibiOS/os/rt/ports/SIMIA32 -I../firmware/ChibiOS/os/rt/include -I../firmware/ChibiOS/os/hal/osal/rt -I../firmware/ChibiOS/os/hal/include -I../firmware/ChibiOS/os/hal/ports/simulator/win32 -I../firmware/ChibiOS/os/hal/ports/simulator -I../firmware/ChibiOS/os/hal/boards/simulator -I../firmware/util -I../firmware/console -I../firmware/console/binary -I../firmware/console/fl_binary -I../firmware/config/engines -I../firmware/ext_algo -I../firmware/controllers -I../firmware/hw_layer/algo -I../firmware/development -I../firmware/controllers/algo -I../firmware/controllers/core -I../firmware/controllers/math -I../firmware/controllers/sensors -I../firmware/controllers/system -I../firmware/controllers/trigger -I../firmware/controllers/trigger/decoders -I../firmware/ChibiOS/os/various -I../firmware/ChibiOS/os/hal/lib/streams -Isimulator ../firmware/controllers/map_averaging.cpp -o build/obj/map_averaging.o



i686-w64-mingw32-g++ -c  -Os  -ffunction-sections -fdata-sections -fno-common -std=c++11 -fno-rtti -fpermissive -fno-exceptions -fno-use-cxa-atexit -Wall -Wextra -Wa,-alms=build/lst/trigger_emulator.lst  -DSIMULATOR -MD -MP -MF .dep/trigger_emulator.o.d -Os  -ffunction-sections -fdata-sections -fno-common -I. -I. -I../firmware/ChibiOS/os/rt/ports/SIMIA32/compilers/GCC -I../firmware/ChibiOS/os/rt/ports/SIMIA32 -I../firmware/ChibiOS/os/rt/include -I../firmware/ChibiOS/os/hal/osal/rt -I../firmware/ChibiOS/os/hal/include -I../firmware/ChibiOS/os/hal/ports/simulator/win32 -I../firmware/ChibiOS/os/hal/ports/simulator -I../firmware/ChibiOS/os/hal/boards/simulator -I../firmware/util -I../firmware/console -I../firmware/console/binary -I../firmware/console/fl_binary -I../firmware/config/engines -I../firmware/ext_algo -I../firmware/controllers -I../firmware/hw_layer/algo -I../firmware/development -I../firmware/controllers/algo -I../firmware/controllers/core -I../firmware/controllers/math -I../firmware/controllers/sensors -I../firmware/controllers/system -I../firmware/controllers/trigger -I../firmware/controllers/trigger/decoders -I../firmware/ChibiOS/os/various -I../firmware/ChibiOS/os/hal/lib/streams -Isimulator ../firmware/development/trigger_emulator.cpp -o build/obj/trigger_emulator.o



i686-w64-mingw32-g++   build/obj/chcore.o build/obj/chsys.o build/obj/chdebug.o build/obj/chvt.o build/obj/chschd.o build/obj/chthreads.o build/obj/chtm.o build/obj/chstats.o build/obj/chdynamic.o build/obj/chregistry.o build/obj/chsem.o build/obj/chmtx.o build/obj/chcond.o build/obj/chevents.o build/obj/chmsg.o build/obj/chmboxes.o build/obj/chqueues.o build/obj/chmemcore.o build/obj/chheap.o build/obj/chmempools.o build/obj/hal.o build/obj/hal_buffers.o build/obj/hal_queues.o build/obj/hal_mmcsd.o build/obj/adc.o build/obj/can.o build/obj/dac.o build/obj/ext.o build/obj/gpt.o build/obj/i2c.o build/obj/i2s.o build/obj/icu.o build/obj/mac.o build/obj/mmc_spi.o build/obj/pal.o build/obj/pwm.o build/obj/rtc.o build/obj/sdc.o build/obj/serial.o build/obj/serial_usb.o build/obj/spi.o build/obj/st.o build/obj/uart.o build/obj/usb.o build/obj/wdg.o build/obj/hal_lld.o build/obj/serial_lld.o build/obj/console.o build/obj/pal_lld.o build/obj/st_lld.o build/obj/map_adjuster.o build/obj/nmea.o build/obj/board.o build/obj/memstreams.o build/obj/chprintf.o build/obj/shell.o build/obj/crc.o build/obj/data_buffer.o build/obj/rfiutil.o build/obj/histogram.o build/obj/main.o build/obj/cyclic_buffer.o build/obj/datalogging.o build/obj/loggingcentral.o build/obj/listener_array.o build/obj/cli_registry.o build/obj/efilib.o build/obj/efilib2.o build/obj/LocalVersionHolder.o build/obj/advance_map.o build/obj/idle_controller.o build/obj/malfunction_central.o build/obj/auto_generated_enums.o build/obj/fuel_math.o build/obj/accel_enrichment.o build/obj/engine_configuration.o build/obj/engine.o build/obj/lcd_menu_tree.o build/obj/event_registry.o build/obj/algo.o build/obj/aux_pid.o build/obj/signal_executor.o build/obj/settings.o build/obj/engine_controller.o build/obj/error_handling.o build/obj/sensor_chart.o build/obj/trigger_emulator_algo.o build/obj/rpm_calculator.o build/obj/trigger_central.o build/obj/spark_logic.o build/obj/main_trigger_callback.o build/obj/trigger_bmw.o build/obj/trigger_mazda.o build/obj/trigger_chrysler.o build/obj/trigger_structure.o build/obj/trigger_decoder.o build/obj/trigger_simulator.o build/obj/trigger_mitsubishi.o build/obj/trigger_nissan.o build/obj/trigger_subaru.o build/obj/trigger_toyota.o build/obj/trigger_gm.o build/obj/trigger_honda.o build/obj/trigger_rover.o build/obj/trigger_universal.o build/obj/pwm_generator_logic.o build/obj/signal_executor_sleep.o build/obj/event_queue.o build/obj/efiGpio.o build/obj/SingleTimerExecutor.o build/obj/tunerstudio_io.o build/obj/tunerstudio.o build/obj/status_loop.o build/obj/console_io.o build/obj/fl_protocol.o build/obj/eficonsole.o build/obj/thermistors.o build/obj/allsensors.o build/obj/map.o build/obj/voltage.o build/obj/maf.o build/obj/tps.o build/obj/ego.o build/obj/hip9011_lookup.o build/obj/EfiWave.o build/obj/avg_values.o build/obj/table_helper.o build/obj/fsio_core.o build/obj/interpolation.o build/obj/fsio_impl.o build/obj/engine_math.o build/obj/pid.o build/obj/biquad.o build/obj/speed_density.o build/obj/engine_sniffer.o build/obj/ford_aspire.o build/obj/custom_engine.o build/obj/MiniCooperR50.o build/obj/acura_rsx.o build/obj/audi_aan.o build/obj/bmw_e34.o build/obj/mazda_miata.o build/obj/mazda_miata_1_6.o build/obj/mazda_miata_vvt.o build/obj/citroenBerlingoTU3JP.o build/obj/dodge_neon.o build/obj/ford_fiesta.o build/obj/ford_1995_inline_6.o build/obj/nissan_primera.o build/obj/mazda_miata_nb.o build/obj/honda_accord.o build/obj/subaru.o build/obj/snow_blower.o build/obj/GY6_139QMB.o build/obj/rover_v8.o build/obj/mazda_323.o build/obj/mazda_626.o build/obj/saturn_ion.o build/obj/sachs.o build/obj/test_engine.o build/obj/mitsubishi.o build/obj/gm_2_2.o build/obj/dodge_ram.o build/obj/vw.o build/obj/dodge_stratus.o build/obj/chevrolet_camaro_4.o build/obj/suzuki_vitara.o build/obj/daihatsu.o build/obj/chevrolet_c20_1973.o build/obj/toyota_jzs147.o build/obj/lada_kalina.o build/obj/geo_storm.o build/obj/zil130.o build/obj/honda_600.o build/obj/ford_festiva.o build/obj/rusEfiFunctionalTest.o build/obj/framework.o build/obj/boards.o build/obj/map_averaging.o build/obj/trigger_emulator.o  -Os  -ffunction-sections -fdata-sections -fno-common  -Wl,-Map=build/rusefi_simulator.map,--cref,--no-warn-mismatch,--library-path=,,--gc-sections,--defsym=__process_stack_size__=0x400,--defsym=__main_stack_size__=0x400 -static-libgcc -static-libstdc++ -lws2_32 -lm -o build/rusefi_simulator.exe


/usr/lib/gcc/i686-w64-mingw32/5.4.0/../../../../i686-w64-mingw32/bin/ld: cannot find : No such file or directory
collect2: error: ld returned 1 exit status
make: *** [rules.mk:149: build/rusefi_simulator.exe] Error 1




**## check this out, an example of a shortened command with most .o removed:
as is, with --library-path=,,**

i686-w64-mingw32-g++    build/obj/map_averaging.o build/obj/trigger_emulator.o  -Os  -ffunction-sections -fdata-sections -fno-common  -Wl,-Map=build/rusefi_simulator.map,--cref,--no-warn-mismatch,--library-path=,,--gc-sections,--defsym=__process_stack_size__=0x400,--defsym=__main_stack_size__=0x400 -static-libgcc -static-libstdc++ -lws2_32 -lm -o build/rusefi_simulator.exe
 > log2 2>err2

/usr/lib/gcc/i686-w64-mingw32/5.4.0/../../../../i686-w64-mingw32/bin/ld: cannot find : No such file or directory
collect2: error: ld returned 1 exit status



## now without --library-path=,,


i686-w64-mingw32-g++    build/obj/map_averaging.o build/obj/trigger_emulator.o  -Os  -ffunction-sections -fdata-sections -fno-common  -Wl,-Map=build/rusefi_simulator.map,--cref,--no-warn-mismatch,--gc-sections,--defsym=__process_stack_size__=0x400,--defsym=__main_stack_size__=0x400 -static-libgcc -static-libstdc++ -lws2_32 -lm -o build/rusefi_simulator.exe
 > log3 2>err3


build/obj/map_averaging.o:map_averaging.cpp:(.text.startup._GLOBAL__sub_I__Z13getMapVoltagev+0x32): undefined reference to `scheduling_s::scheduling_s()'
build/obj/map_averaging.o:map_averaging.cpp:(.text.startup._GLOBAL__sub_I__Z13getMapVoltagev+0x42): undefined reference to `scheduling_s::scheduling_s()'
build/obj/map_averaging.o:map_averaging.cpp:(.text.startup._GLOBAL__sub_I__Z13getMapVoltagev+0x4d): undefined reference to `scheduling_s::scheduling_s()'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text$_Z19initTriggerEmulatorP7LoggingP6Engine+0x1a): undefined reference to `getConfigurationName(engine_type_e)'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text$_Z19initTriggerEmulatorP7LoggingP6Engine+0x2a): undefined reference to `print(char const*, ...)'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text$_Z19initTriggerEmulatorP7LoggingP6Engine+0x36): undefined reference to `triggerSignal'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text$_Z19initTriggerEmulatorP7LoggingP6Engine+0x40): undefined reference to `triggerSignal'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text$_Z19initTriggerEmulatorP7LoggingP6Engine+0x4a): undefined reference to `triggerSignal'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text$_Z19initTriggerEmulatorP7LoggingP6Engine+0x59): undefined reference to `initTriggerEmulatorLogic(Logging*, Engine*)'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text.startup._GLOBAL__sub_I__Z19initTriggerEmulatorP7LoggingP6Engine+0xc): undefined reference to `OutputPin::OutputPin()'
build/obj/trigger_emulator.o:trigger_emulator.cpp:(.text.startup._GLOBAL__sub_I__Z19initTriggerEmulatorP7LoggingP6Engine+0x16): undefined reference to `OutputPin::OutputPin()'

**Comment by rusefi** [comment]
simulator compiler for me if I remove

,--library-path=$(RULESPATH)

from rules.mk

can you please try removing 

,--library-path=$(RULESPATH)

and see if it would compile for you?

**Comment by fpoussin** [comment]
I'll have a look at these parameters, it compiles fine for me.

There's not point in keeping the chibios_16 folder to keep the PR smaller... We're not even using it.
Since it's all done in the first commit it won't even make a difference when it comes to see the changes.
Also I simply can't undo it without restarting the whole process of cherry picking.

**Comment by fpoussin** [comment]
Links fine without the flag, I removed it.

**Comment by rusefi** [comment]
will commit fix in a second

image

**Comment by fpoussin** [comment]
Sweet, I'll open a new pull request for future fixes to that branch, then when everything looks good we can merge to master.

**Comment by rusefi** [comment]
Simulator is also affected

Command [reset_engine_chart] executed in 505
time,.1000f,rpm,200,mode,54,CLT,.100f,TPS,.100f,vbatt,.100f,IAT,.100f,MAP,.100f,afr,.100f,target,.100f,ENGINE_LOAD,.100f,dwell,.100f,knck_c,f,knck_v,.100f,warn,19,error,6046,
Sending packet 4F 
Waiting for 2 byte(s): output channels header


looks like any float number is printeed as .100f or 0.100f? Looks like %f is broken?

**Pull request merged**
