### PR TITLE
fix gm 24x decoder

### PR DESCRIPTION
**Pull request by mck1117**
Documentation online said that the teeth are 3 or 12 degrees long.  My car and an oscilloscope says that they're 5 and 10 degrees long (which actually makes more sense).

### CODE REVIEW

**Comment by mck1117** [comment]
hmm - looks like this trips a fatal error when trying to calculate the sync point

**Comment by rusefi** [comment]
what is the state of this PR? does it pass unit tests? do simulator and firmware compile?

**Comment by mck1117** [comment]
It compiles, but tests (and firmware) fail because the sync ratios need tweaking.

**Comment by mck1117** [comment]
This is now actually fixed - some of the logic was flipped too.

Verified with unit tests, and by getting a real ECU to sync with a real engine:

https://www.youtube.com/watch?v=t8rsThX2rtE

(pardon the crappy video, this was shot at night, thru the gap in the open hood, with my laptop sitting on the slam panel up front)

**Comment by mck1117** [comment]
fyi we're syncing on these three rising edges, sync ratio gaps 2-0.5-2, ending at 310 degrees:

image

**Pull request merged**
