### PR TITLE
we have other places to set these MCU values

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by mck1117** [comment]
looks like kinetis/cypress `hw_ports.mk` will need `MCU = cortex-m4`

image

**Comment by rusefillc** [comment]
what a mess :( looks like not worth touching at all

**Comment by mck1117** [comment]
what? you were two lines away from it working

**Comment by rusefillc** [comment]
i am not sure that new working state was better than old working state

**Pull request closed without merging**
