### PR TITLE
OpenBLT: add as submodule under firmware/ext

### PR DESCRIPTION
**Pull request by dron0gus**
OpenBLT is forked for RusEFI, rusefi_prod brunch is used.

### CODE REVIEW

**Comment by rusefillc** [comment]
github actions did not like this custom submodule syntax

let's use syntax matching other submodule usages?

**Comment by dron0gus** [comment]
> let's use syntax matching other submodule usages?

Ops. This was fixed in initial (BIG) PR. Will cherry pick fix.

**Comment by rusefillc** [comment]
Do you want to specify branch since we had a fix?

**Comment by dron0gus** [comment]
```
$ git submodule status
...
 d37f1887f7a03af9b563bbcaa51fe65e8e7d5fa8 ext/openblt (heads/rusefi_prod)
```
I always thought submodules are commit-id-related. Autotracking of remote branch was introduced https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule/18799234#18799234 but my Ubuntu git is still too old.

**Comment by rusefillc** [comment]
they say Git 2.22, Q2 2019

**Comment by dron0gus** [comment]
My git is 2.17.1. :(

**Comment by rusefillc** [comment]
time for ```sudo apt update```? :)

**Pull request merged**
