### PR TITLE
better VSS configuration

### PR DESCRIPTION
**Pull request by mck1117**
Instead of a mystery ratio that users have to calculate, input things they can actually measure or count: wheel turns per km, axle ratio, and vss tooth count.

first part of #3537

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 poke :)

**Comment by rusefillc** [comment]
HW CI red?

**Comment by mck1117** [comment]
this damn near killed me, the offset for the VSS sensor was WRONG!

**Comment by mck1117** [comment]
oh my god it passed we're green

**Comment by rusefillc** [comment]
Code generator on the way

**Pull request merged**
