### PR TITLE
gcc11

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by rusefillc** [comment]
https://stackoverflow.com/questions/73063104/gcc-11-arm-none-eabi-fails-to-find-file-which-gcc-10-does-find

**Comment by rusefillc** [comment]
https://community.arm.com/support-forums/f/compilers-and-libraries-forum/52288/arm-none-eabi-gcc-11-version-compiler-asmbler-failed has more details

**Comment by rusefillc** [comment]
@dron0gus do you like GCC11, assembly and OpenBLT? ``AFLAGS      = $(CFLAGS) -Wa,-I$(INCDIR)`` does not do the trick for me :(

**Comment by rusefillc** [comment]
@nmschulte this one is another gcc11 drama - see comments above, OpenBLT assembly import behaving differently due to compiler settings differences

**Comment by mck1117** [comment]
this needs to switch HW CI compiler config too

**Comment by rusefillc** [comment]
> this needs to switch HW CI compiler config too

Yes, but we are totally not there yet - at the moment a few of GHA are red.

**Comment by rusefillc** [comment]
@nmschulte i guess gcc11 is asking for a bigger change for cypress :(

**Comment by nmschulte** [comment]
This is odd, as cypress builds just fine for me locally with this toolchain (and gcc version 11.3.1 20220712 (15:11.3.rel1-1)).

**Comment by nmschulte** [comment]
This is odd, as cypress doesn't fail that way with this toolchain (and gcc version 11.3.1 20220712 (15:11.3.rel1-1)); instead it fails at linking:

```
Linking build/rusefi.elf
lto-wrapper: warning: Options to '-Xassembler' do not match: -alms=build/lst/check.lst, -alms=build/lst/crt1.lst, dropping all '-Xassembler' and '-Wa' options.
/tmp/ccmkV0aI.s: Assembler messages:
/tmp/ccmkV0aI.s:16: Warning: ignoring changed section attributes for .data
In function 'intFlashRead',
    inlined from 'backupInit' at ./hw_layer/ports/cypress/backup_ram.cpp:28:14:
./hw_layer/ports/cypress/flash_int.cpp:131:15: error: 'memcpy' reading 24 bytes from a region of size 0 [-Werror=stringop-overread]
  131 |         memcpy(destination, (char*) source, size);
      |               ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: arm-none-eabi-gcc returned 1 exit status
compilation terminated.
/home/nmschulte/.rusefi-tools/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.2.1/../../../../arm-none-eabi/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [ChibiOS/os/common/startup/ARMCMx/compilers/GCC/mk/rules.mk:217: build/rusefi.elf] Error 1
```

**Comment by rusefillc** [comment]
I've definitely seen that "error: 'memcpy' reading 24 bytes from a region of size 0"

**Comment by nmschulte** [comment]
I suspect there's another GCC or so installed on the CI agent; is it okay to create test PRs (with `gcc -v`) to get more diagnostic and invoke them via PR, or will that use precious CI credits or so?

**Comment by mck1117** [comment]
> I suspect there's another GCC or so installed on the CI agent; is it okay to create test PRs (with `gcc -v`) to get more diagnostic and invoke them via PR, or will that use precious CI credits or so?

the gates already run `gcc -v`

image

**Comment by nmschulte** [comment]
I'm able to get around the error about `flash_int`/`backup_ram` (making `flashaddr_t` to `uint32_t *`), but running into issues about `CanfdGetRxFIFO`:
```
./config/boards/cypress/OS/os/hal/ports/Cypress/PDL/driver/can/canfd.c: In function 'CanfdGetRxFIFO.part.0.constprop':
./config/boards/cypress/OS/os/hal/ports/Cypress/PDL/driver/can/canfd.c:1734:59: error: '__builtin_memmove' reading between 4 and 1020 bytes from a region of size 0 [-Werror=stringop-overread]
 1734 |                                 pstcRxBuffer->data[u8Idx] = pstcMsg->data[u8Idx];
      |
```
Using `memcpy` produces similar error, but indexing `pstcMsg->data` directly produces no such error.  Not sure how to convince the linker about this one.

**Comment by rusefillc** [comment]
@mck1117 shall we just lower the guard from error to warning for now?

**Comment by nmschulte** [comment]
The 11.3 version of the toolchain works about this, versus the chosen 11.2.

**Comment by nmschulte** [comment]
In fact, v11.3 avoids all of these issues.

**Comment by mck1117** [comment]
go ahead and pr 11.3 in to this branch then!

**Comment by mck1117** [comment]
Iiiiiii would require exactly one compiler version. Fewer gotchas.

**Comment by rusefillc** [comment]
@nmschulte @mck1117 can you help by PRing relevant change into chech.s?

**Comment by rusefillc** [comment]
@nmschulte @mck1117 please help - one tasks still has 10.3 somehow? do we need to extract some logic into shared script so that we do not have so many places to make a change?

**Comment by rusefillc** [comment]
@nmschulte let me abuse your kindness more see #4759 - looks like a clean-un is needed before we switch compiler

**Comment by rusefillc** [comment]
Next steps are PR proper gcc into https://github.com/rusefi/build_support and switch script to github consumption to reduce GCC server load?

**Pull request merged**
