### PR TITLE
missed e85 cranking autoscale

### LINKED ISSUE #4100: E85 cranking correction is messing with Jesse
when moving from older firmware(1/24) to latest release(3/16) the lemon presents a no start symptom.

Observations- 
1- during cranking, there is only one flash of all 4 injectors (simultaneous) 
2- after being warmed up, it will start on the newer firmware.  It is noted that the single simultaneous injection is enough for it to exit "cranking" and enter "running" mode.  This is clear by watching the injector LEDs on the board. 
3- If you raise the "cranking" rpm limit higher, it will attempt to start on that single simultaneous injection but will never enter "running" injection mode.  This results again in the no start.
4- with 1/24 firmware, you can several quick simultaneous pulses from the injectors prior to entering "running" injection mode.

Log with 1/24 firmware
https://rusefi.com/online/view.php?log=758

Log with 3/16 firmware
https://rusefi.com/online/view.php?log=757

Something in the new firmware is preventing the ecu from injection during cranking.

### PR DESCRIPTION
**Pull request by mck1117**
fix #4100

### CODE REVIEW

**Comment by rusefillc** [comment]
can this be covered by a test? should this be covered by a test?

**Comment by mck1117** [comment]
I do not understand this non-deterministic occasional MRE F4 failure

image

**Comment by rusefillc** [comment]
@mck1117 yes I know :(

**Comment by mck1117** [comment]
> can this be covered by a test? should this be covered by a test?

Unfortunately if we do `myThing = 2; assert(myThing == 2);` that works even if autoscale is missed.

We could maybe fix this in the config generator by generating an error or warning if you have non-1 scale without the autoscale keyword present.

**Comment by rusefillc** [comment]
force autoscale in case of any scale? I like it!

**Comment by mck1117** [comment]
> force autoscale in case of any scale? I like it!

We could force it, or at least complain for now.

**Comment by rusefillc** [comment]
@mck1117 
```
$ ./gen_config.sh | grep RRRR
mkdir: cannot create directory ‘build’: File exists
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='timeConstant', type='uint16_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='deadband', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='minAfr', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='maxAfr', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='knockRetardAggression', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='knockRetardReapplyRate', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='dwellVoltageCorrVoltBins', type='uint8_t', arraySizes=[8]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='dwellVoltageCorrValues', type='uint8_t', arraySizes=[8]}
RRRRRRRRRRRRRRRR Unexpected scale of {1/1000} without autoscale on ConfigField{name='applyNonlinearBelowPulse', type='uint16_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.001 without autoscale on ConfigField{name='multisparkSparkDuration', type='uint16_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.001 without autoscale on ConfigField{name='multisparkDwell', type='uint16_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 5 without autoscale on ConfigField{name='tchargeBins', type='uint8_t', arraySizes=[16]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.01 without autoscale on ConfigField{name='tchargeValues', type='uint8_t', arraySizes=[16]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='triggerCompCenterVolt', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='triggerCompHystMin', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='triggerCompHystMax', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim', type='int8_t', arraySizes=[12]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim1', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim2', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim3', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim4', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim5', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim6', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim7', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim8', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim9', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim10', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim11', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='fuelTrim12', type='int8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of {1/100} without autoscale on ConfigField{name='mapEstimateTable', type='uint16_t', arraySizes=[16, 16]}
RRRRRRRRRRRRRRRR Unexpected scale of {1/10} without autoscale on ConfigField{name='lambdaTable', type='uint8_t', arraySizes=[16, 16]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.02 without autoscale on ConfigField{name='tcu_pcAirmassBins', type='uint8_t', arraySizes=[8]}
```

**Pull request merged**
