### PR TITLE
Try pulling first

### LINKED ISSUE #2446: false positive GHA drama
why did https://github.com/rusefi/rusefi/runs/2092138201 fail?

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
I *think* this should fix #2446. On the other hand I understand git poorly, so I don't have a good understanding of what issues doing it this way could cause.

### CODE REVIEW

**Comment by rusefillc** [comment]
good change that it should be fetch and merge not pull, i think :(

we need to begin from beginning. what is image we push and why do we push so often

**Comment by mck1117** [comment]
fetch + merge == pull (mostly)

I'm not in favor of this though, since it'll pollute the history with /even more/ commits (merge commits).

**Comment by chuckwagoncomputing** [comment]
It'll only create a commit if there are actually changes that have been pushed while the action is running, right?

**Comment by chuckwagoncomputing** [comment]
The unit test workflow only pushes unit_tests/triggers.txt.

**Comment by rusefillc** [comment]
trigher is only updated if shape has changed?

**Comment by mck1117** [comment]
I'm not sure this is fixed

**Comment by rusefillc** [comment]
something is fixed since unit tests were finally able to commit fresh triggers

**Comment by mck1117** [comment]
I suspect a change that causes a generated config commit would cause the unit test build to fail to commit, it didn't happen because the generated config commit hasn't happened

**Comment by chuckwagoncomputing** [comment]
I'm confused about what's going on here. @rusefillc, did you think the issue was fixed without this PR? @mck1117, what do you think would be a proper fix for this?

**Comment by rusefillc** [comment]
we had multiple different issues

most urgent issue was fixed without this PR

what @mck1117 describes is a separate less urgent scenario

at the moment master is broken for third issue around GH packages?

**Comment by rusefillc** [comment]
Did not work? https://github.com/rusefi/rusefi/runs/2104185467?check_suite_focus=true

**Pull request merged**
