### PR TITLE
fix type mismatch

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
This fixes the title issue of #1802

### CODE REVIEW

**Comment by rusefillc** [comment]
at the moment this PR is just the bare minimum of the fix

let's do better - let's invest a bit into quality. at least we need field comment that units are seconds
also while init method type was changed, class field was not? let's do better than just bare minimum please.

**Review by rusefillc — CHANGES_REQUESTED** [review]
at least config type code comment, class field type

maybe also new time type for config?

**Comment by chuckwagoncomputing** [comment]
Config is already efitimesec_t, not sure what more you want for this issue.

**Comment by rusefillc** [comment]
config is startCrankingDuration

startCrankingDuration is not efitimesec_t

startCrankingDuration is int16_t

actually startCrankingDuration already has "Seconds" human-readable for TS units 
```
	int16_t startCrankingDuration;Maximum time to crank starter;"Seconds",      1,      0,       0, 30,      0
```


but if a developer is looking at engine_configuration_generated_structures.h
```
	/**
	 * Maximum time to crank starter
	 * offset 826
	 */
	int16_t startCrankingDuration;
```
there is no reference to seconds

we can at least change "Maximum time to crank starter" to "Maximum time to crank starter, in seconds"

or maybe ideally change int16_t to efitimesec16_t

**Comment by chuckwagoncomputing** [comment]
Not sure why I thought it did.

**Pull request merged**
