### PR TITLE
Fix #1590

### LINKED ISSUE #1590: Build Orthogonality Issues
If any gen_config fails, all firmware builds fail.
If console build fails, all firmware builds fail.
If simulator build fails, all firmware builds fail.
And probably others too.

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
@mck1117  Can you review this?

### CODE REVIEW

**Comment by rusefi** [comment]
Please elaborate what's going on here? Do we need some documentation right in the repo already...?

**Comment by chuckwagoncomputing** [comment]
1: Breaks config scripts apart so that GHA can call only the script needed for the build
2: GHA builds sim, console, and packages only on a push to master, but still builds firmware on a PR.

**Comment by rusefi** [comment]
2. i do not get it. how do we guarantee that sim & console are not broken by PR if we do not build those in PR?

**Comment by chuckwagoncomputing** [comment]
Oh I didn't say that right. They are built, just not in the build-firmware workflow. So if they break, they don't break the firmware build.

**Comment by mck1117** [comment]
Can we put this awesome diagram (assuming it's accurate) in a readme in the `.github/workflows` folder?

https://github.com/rusefi/rusefi/issues/1590#issuecomment-657136285

**Comment by chuckwagoncomputing** [comment]
I'm working on updating it to what I actually implemented.

**Comment by chuckwagoncomputing** [comment]
Oops didn't mean to close

**Comment by chuckwagoncomputing** [comment]
Also I don't know what I did but somewhere I messed up the commit history pretty badly. Only the commits from yesterday are actually relevant. How do I fix that, or is it not important?

**Comment by rusefi** [comment]
default merge here is with squash anyway, history is not preserved exactly anyway. as long as the total diff is still valid are we good?

**Comment by rusefi** [comment]
merge? work in progress? else?

**Comment by chuckwagoncomputing** [comment]
Looks ready for merge to me.

**Pull request merged**
