### PR TITLE
Remove warmup afr pid

### PR DESCRIPTION
**Pull request by mck1117**
Remove the warmup afr pid - it does the same thing as the normal short-term fuel PID, plus the normal warmup fuel curve.

Also saves 576 bytes of code space at level `-O2`, a handful of branches, and 56 bytes + 1 bit of config space.

(requires a config re-gen to compile)

### CODE REVIEW

**Comment by mck1117** [comment]
poke

**Comment by rusefi** [comment]
Why now? Is anything driving this change?

I am jet lagged now, I would prefer to think about this in a couple days later once/if I gain my brain back.

**Comment by mck1117** [comment]
There's not a particular rush, no.  It's just that this functionality was causing bloat, unnecessary complexity in `periodicFastCallback`, and potential confusion for users about a feature that overlaps partially (in a sort of confusing way) with others.  Plus it's 56 bytes of config we can reclaim.

**Comment by mck1117** [comment]
After further thought - this is actually broken, and maybe dangerous.  This function tries to adjust the fueling output to match the AFR in the `warmupTargetAfr` table (a function of coolant temperature), effectively **ignoring** the values from the normal AFR target table.

If you have a value of 14.7 (stoichiometric) in this table, and stand on the gas, the ECU will try to correct BACK to 14.7 even if the open-loop AFR target is something different.  Running at 14.7 under boost WILL overheat pistons, even when the engine is cold.

**Comment by rusefi** [comment]
@mck1117 can you please rebase to resolve the merge conflict? or what is the smart way for me to handle it?

**Comment by mck1117** [comment]
yes - I can resolve

**Comment by mck1117** [comment]
fixed - ready for merge

**Pull request merged**
