### PR TITLE
Add TCU Solenoid debug fields

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
#2118

### CODE REVIEW

**Comment by rusefillc** [comment]
@chuckwagoncomputing can we fix "build simulator" to invoke gen_enum for this task to get green?

**Comment by rusefillc** [comment]
merge or rebase to consume sim change?

**Comment by chuckwagoncomputing** [comment]
I guess unit tests needs it too.

**Comment by rusefillc** [comment]
not green?

**Comment by chuckwagoncomputing** [comment]
Nope. More different problems.

**Comment by rusefillc** [comment]
Great progress! We are eliminating false failures to see true failures :)

**Pull request merged**
