### PR TITLE
Draft: Common factor for all corrections

### PR DESCRIPTION
**Pull request by 960**
Initial start of changing all correction factors to % to reduce confusion.

Use 1d arrays for corrections for usability.

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by 960** [comment]
Will turn them into this format:

javaw_aOpXCxG5A4

**Comment by rusefi** [comment]
Add to whitelist

**Comment by rusefi** [comment]
A change like this was supposed to be discussed in advance

Also I see that we are throwing multiple changes together. We need a different approach considering .input and .txt changes

**Comment by 960** [comment]
It's been discussed, but never came to any conclution.

You'll keep it as is.

**Pull request closed without merging**
