### PR TITLE
Don't download ARM Gnu toolchain if present

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
This enables self-hosted runners to pre-download the arm-none-eabi toolchain at build time.
The script checks the checksum of one of the executables, so that we are sure to be running the correct toolchain version.

### CODE REVIEW

**Comment by mck1117** [comment]
> This enables self-hosted runners to pre-download the arm-none-eabi toolchain at build time.

what's the actual observable change/purpose?

**Comment by chuckwagoncomputing** [comment]
Currently (pre-this-pr), the firmware workflow always downloads the toolchain, deleting it if it already exists.
This PR makes it so that if the toolchain already exists, it isn't downloaded again.

**Comment by mck1117** [comment]
I must be missing some piece, is there a way to have it pre-placed on a GHA runner?

**Comment by chuckwagoncomputing** [comment]
It's possible to do so by providing a Docker container, but that's beside the point of this PR.

Right now, this is just a time-save for self hosted runners. The current Dockerfile of https://github.com/ZHoob2004/rusefi-ci/ downloads the toolchain, but doing so is useless as it just gets deleted and re-downloaded on every job.

**Review by mck1117 — APPROVED** [review]

**Comment by chuckwagoncomputing** [comment]
If we run our own Docker container on github-hosted runners, we won't need to run this script in the workflow.
We currently run this script in the workflow because we don't have arm-none-eabi present on github-hosted runners.
We have the power to have arm-none-eabi present on self-hosted runners.
Currently, this does us no good because the workflow just deletes it and re-downloads it.
Merging this PR will correct this, saving time for self-hosted runners.

**Comment by nmschulte** [comment]
Do the github-hosted runners get re-used or something; is that why this is a win w/o self-hosted?

**Comment by chuckwagoncomputing** [comment]
They don't unfortunately. This is a win because I can self-host my own runners and reap the advantages even if there aren't any on the main repository.

**Pull request merged**
