### PR TITLE
remove mock adc

### PR DESCRIPTION
**Pull request by mck1117**
#3672

### CODE REVIEW

**Comment by rusefillc** [comment]
same unit tests fails extremely consistently there might be a signal there

any chance to split PR into smaller ones?

**Comment by mck1117** [comment]
I really don't understand how changing two lines in a hardware CI test makes a java unit test fail

**Comment by rusefillc** [comment]
I have little faith in that unit test I am pretty sure that one of these real-tcp-ip tests fails sometimes. Maybe very bad luck strike.

But I am not open to the risk of merging this, maybe smaller PRs are the way to go.

**Comment by rusefillc** [comment]
Amazing it just makes no sense.

**Comment by mck1117** [comment]
I had accidentially checked in `Fields.java` before, which is the only explanation I can come up with

**Pull request merged**
