### PR TITLE
yet more TS sanity

### PR DESCRIPTION
**Pull request by mck1117**
- extracts interface to TsChannelBase
- implementation in ts_channel_s for now, to be split out by underlying channel type

more continuation of #2381

### CODE REVIEW

**Comment by rusefillc** [comment]
why refactoring this now, how did you end up in TS code?

**Comment by mck1117** [comment]
I ended up in TS code while trying to simplify mcuconf/halconf/etc, and came across this monstrosity:
image
In no world is this reasonable code 🙂

**Comment by rusefillc** [comment]
So a https://en.wikipedia.org/wiki/Rabbit_hole ?

**Comment by mck1117** [comment]
Probably yes, but the rabbit was bored on a 6.5hr flight, so it did some digging deep in the hole.

**Pull request merged**
