### PR TITLE
add option to invert vvt control

### PR DESCRIPTION
**Pull request by mck1117**
#4424

### CODE REVIEW

**Comment by rusefillc** [comment]
Do we really need 4 oprions? Can we see bank 1 anx bank two working differently?

**Comment by rusefillc** [comment]
Lets start with only two bits

**Comment by mck1117** [comment]
> Do we really need 4 oprions? Can we see bank 1 anx bank two working differently?

that's a fair point, I don't think any engines have fundamental control differences between banks

**Comment by rusefillc** [comment]
please CHANGELOG

**Pull request merged**
