### PR TITLE
why is injector model an engine model if it implements none of the me…

### PR DESCRIPTION
**Pull request by rusefillc**
@mck1117 let me call you about this one

### CODE REVIEW

**Comment by mck1117** [comment]
I don't think it needs to be an engine module. Pulling it out is fine.

**Comment by mck1117** [comment]
wasn't me 🤷‍♂️

image

**Comment by rusefillc** [comment]
@mck1117 separate problem is the fact that I am unable to remove EngineModule from here, I do not understand how to write this in a happy way

**Comment by mck1117** [comment]
want me to PR?

**Comment by rusefillc** [comment]
@mck1117 yes please!

**Comment by rusefillc** [comment]
@mck1117 please PR if you have a chance

**Comment by mck1117** [comment]
unfortunately mock able doesn't work outside of the type list

**Comment by rusefillc** [comment]
Exactly https://github.com/rusefi/rusefi/pull/4600

**Pull request closed without merging**
