### PR TITLE
more CAN verbose

### PR DESCRIPTION
**Pull request by mck1117**
- Send VVT positions and targets
- Send both lambdas 
- Send flex percent #4401
- Send both fuel pressures #4401

Also don't directly read the `Value` field of `expected`, since it may now contain garbage in case of invalid, instead of 0.

### CODE REVIEW

**Comment by rusefillc** [comment]
looks cool and abandonet, let me give this a try

**Comment by mck1117** [comment]
let me resurrect

**Comment by mck1117** [comment]
in the process of fixing another PR

**Comment by mck1117** [comment]
shouuuuld be happy now, let's see if green check marks agree

**Comment by mck1117** [comment]
it's happy!

**Pull request merged**
