### PR TITLE
don't build OS lib

### LINKED ISSUE #2698: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
WSL2
unix eclipse via X windows

eclipse seems to be thinking that this warning is an error?

image

image

image

### PR DESCRIPTION
**Pull request by mck1117**
fixes #2698 by not even compiling that file

### CODE REVIEW

**Comment by rusefillc** [comment]
legit red in unit tests?

**Comment by mck1117** [comment]
I think it's legit yeah

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mck1117** [comment]
Ok now we're good!

**Comment by rusefillc** [comment]
Ty!!!

**Pull request merged**
