### PR TITLE
correct batch fuel cylinder pairing

### LINKED ISSUE #1593: Batch fuel cylinder pairings are wrong
8 cylinder engine, firing order 18726543.

image

Cylinder pairings in the above trace:
1-5, 2-6, 3-7, 4-8

In reality they should be: 1-6, 8-5, 7-4, 2-3

Potentially related to #1592

### PR DESCRIPTION
**Pull request by mck1117**
fix #1593

### CODE REVIEW

**Comment by mck1117** [comment]
tests need some changes - will fix in the morning

**Comment by rusefi** [comment]
unit test please?

**Comment by rusefi** [comment]
poke @mck1117

**Comment by rusefi** [comment]
we need a unit test to cover this issue. I see logic change with zero test changes

**Pull request merged**
