### PR TITLE
simulator job does not take proper branch name

### LINKED ISSUE #6904: simulator job does not take proper branch name
```
I 240911 133939.846 [ECU Communication Executor1] LinkManager - class com.rusefi.io.LinkManager$4: Opening TCP port: 29001
I 240911 133939.866 [[start] TCP reader1] ByteReader - [start] Running TCP connection loop
I 240911 133939.872 [ECU Communication Executor1] BinaryProtocol - Got [rusEFI .2024.09.11.f407-discovery.3260823191] signature
I 240911 133940.306 [ECU Communication Executor1] IniFileModel - Reading /home/runner/.rusEFI/ini_database/3260823191.ini
```

note lack of branch name between ``rusEFI .2024``

### PR DESCRIPTION
**Pull request by FDSoftware**
fixes #6904 

note: needs testing, I can't reproduce with a user created fork:
https://productionresultssa13.blob.core.windows.net/actions-results/be683b96-bc09-43ac-a92a-b37cc8f8a0cf/workflow-job-run-c9cfbd07-d407-5e60-840b-fa00e0d20bac/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-06T01%3A59%3A59Z&sig=OE3UsX7RCIDA1w4j2wtFekCmwdy8E2Z53nyrKdLo6FQ%3D&ske=2024-11-06T13%3A02%3A09Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-06T01%3A02%3A09Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-06T01%3A49%3A54Z&sv=2024-08-04

```
2024-10-31T18:12:58.2207843Z       |                                                              ^
2024-10-31T18:12:58.2209765Z ../firmware/console/binary/signature.cpp:29:47: note: ‘#pragma message: TS_SIGNATURE: rusEFI feature/devcontainer.2024.10.31.f407-discovery.496795309’
2024-10-31T18:12:58.2211704Z    29 | #pragma message ("TS_SIGNATURE: " TS_SIGNATURE)
2024-10-31T18:12:58.2212458Z       |     
```

### CODE REVIEW

**Comment by FDSoftware** [comment]
@rusefillc seems to be ok now:

` note: ‘#pragma message: TS_SIGNATURE: rusEFI bugfix/#6904.2024.11.06.f407-discovery.2671730258’`

`[ECU Communication Executor1] BinaryProtocol - Got [rusEFI bugfix/#6904.2024.11.06.f407-discovery.2671730258] signature`

https://productionresultssa18.blob.core.windows.net/actions-results/5e79c8dd-7686-4cc2-b349-f278d9d89870/workflow-job-run-c9cfbd07-d407-5e60-840b-fa00e0d20bac/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-06T02%3A35%3A05Z&sig=AXhL0JXbsMjrVQe7y4Ak%2F7rqK0DUAbMR4Tu57%2B%2Bacek%3D&ske=2024-11-06T13%3A02%3A14Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-06T01%3A02%3A14Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-06T02%3A25%3A00Z&sv=2024-08-04

**Comment by rusefillc** [comment]
At the moment we have three cases ``echo AUTOMATION_REF=${{github.ref_name}} >> $GITHUB_ENV" >> $GITHUB_ENV``

I guess we have to add a code comment explaining why we introduce inconsistency and why three spots would be ref_name while one would be head_ref?

**Comment by FDSoftware** [comment]
> At the moment we have three cases `echo AUTOMATION_REF=${{github.ref_name}} >> $GITHUB_ENV" >> $GITHUB_ENV`
> 
> I guess we have to add a code comment explaining why we introduce inconsistency and why three spots would be ref_name while one would be head_ref?

added it, please correct me if I wrote it wrong because I have kindergarten english :joy:

**Comment by rusefillc** [comment]
Comment mentions PR twice but why does this matter?

I did https://github.com/rusefi/rusefi/commit/24059240dc6348ef5448c4d86c91fb08c7449657

Is anything wrong about https://github.com/rusefi/rusefi/commit/24059240dc6348ef5448c4d86c91fb08c7449657 ? What is broken about https://github.com/rusefi/rusefi/commit/24059240dc6348ef5448c4d86c91fb08c7449657?

**Comment by FDSoftware** [comment]
> Comment mentions PR twice but why does this matter?
> 
> I did [2405924](https://github.com/rusefi/rusefi/commit/24059240dc6348ef5448c4d86c91fb08c7449657)
> 
> Is anything wrong about [2405924](https://github.com/rusefi/rusefi/commit/24059240dc6348ef5448c4d86c91fb08c7449657) ? What is broken about [2405924](https://github.com/rusefi/rusefi/commit/24059240dc6348ef5448c4d86c91fb08c7449657)?

For nightly/LTS releases nothing, for pull requests the only thing is that instead of the branch name it will show "7047/merge" taking this pr as an example, but if we are satisfied with that we don't have to do anything else and we can close this pr and the linked issue.

**Comment by rusefillc** [comment]
@FDSoftware thank you for the fix for nightly/LTS, I think that's the only thing we care about!

**Pull request closed without merging**
