### PR TITLE
Brain pin is enum class

### PR DESCRIPTION
**Pull request by mck1117**
Make `brain_pin_e` an `enum class`, instead of c-style `enum`. This lets us explicitly size it without any magic - it's now forced to be a uint8_t.

This is 90% a regex find-replace of `GPIO([A-Z])_([0-9]+)` -> `Gpio::$1$2`, with a few real edits to the config generator and a few functions that touch this enum.

### CODE REVIEW

**Comment by rusefillc** [comment]
scary changes to scripts

image

**Comment by mck1117** [comment]
> scary changes to scripts

Works fine.

image

**Comment by rusefillc** [comment]
ohh it's pretty green?

**Comment by rusefillc** [comment]
we have a conflict with 4chan fix sorry

**Pull request merged**
