### PR TITLE
Adc improvements adc3

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by mck1117** [comment]
please wait on this change for my PR on ADC reorder to go in

**Comment by rusefillc** [comment]
@dron0gus please rebase on master since we have relevant changes

**Comment by rusefillc** [comment]
@dron0gus what is the plan for this PR? close or rebase or else? at the moment it does not build

**Comment by dron0gus** [comment]
@rusefillc someday i'll rebase and fix...

**Comment by rusefillc** [comment]
Let keep it open as a reminder of a dream?

**Comment by dron0gus** [comment]
Ok. :)

**Comment by mck1117** [comment]
this would be pretty easy to refactor now to sample adc3 channels in `stm32_adc_v2.cpp`

**Comment by mck1117** [comment]
....in a way that doesn't require 400 lines of code

**Pull request closed without merging**
