### PR TITLE
Egt fixes

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by zed65** [comment]
egtread in console:
2024-03-11_22_26_12_989: EngineState: Reading egt(s)
2024-03-11_22_26_12_989: EngineState: egt1: code=4 (no reply)
2024-03-11_22_26_12_989: EngineState: egt2: code=5 (not enabled)
2024-03-11_22_26_12_990: EngineState: egt3: code=5 (not enabled)
2024-03-11_22_26_12_990: EngineState: egt4: code=5 (not enabled)
2024-03-11_22_26_12_991: EngineState: egt5: code=5 (not enabled)
2024-03-11_22_26_12_997: EngineState: egt6: code=5 (not enabled)
2024-03-11_22_26_12_999: EngineState: egt7: code=5 (not enabled)
2024-03-11_22_26_13_000: EngineState: egt8: code=5 (not enabled)
2024-03-11_22_26_13_001: EngineState: confirmation_egtread:7

**Comment by zed65** [comment]
Just as a sanity check I loaded an older firmware and the egt worked, so the hardware seems to work

**Comment by dron0gus** [comment]
@zed65 hope to get my hand on MAX31855 tomorrow. Sorry for using you as a tester.

**Comment by zed65** [comment]
@dron0gus No worries, tell me if there is anything more I can do. I can bring out the scope probes if you want :)

**Pull request merged**
