### PR TITLE
fix sequential mode cranking

### PR DESCRIPTION
**Pull request by mck1117**
We need to force "two wire wasted" mode when cranking in sequential mode.  If we don't, the engine will only get a chance to start on half the cylinders!

### CODE REVIEW

**Comment by rusefillc** [comment]
Let's PR a failing test first, and then include a fix to the test into this PR?

I know it's boring but that's the way to gain safety in the future.

**Comment by rusefillc** [comment]
@mck1117 poke :)

**Comment by rusefillc** [comment]
@mck1117 poke - close or move forward with test?

**Comment by rusefillc** [comment]
@mck1117 can we add failing unit test?

**Comment by mck1117** [comment]
yes, I will, just wanted to add fuel part before I forgot about it

**Comment by rusefillc** [comment]
ty for sweet progress :)

**Comment by rusefillc** [comment]
@mck1117 poke :)

**Comment by rusefillc** [comment]
@mck1117 can you please rebase?

**Comment by rusefillc** [comment]
@mck1117 do we have a plan? :)

**Comment by rusefillc** [comment]
Shall we add fancy failing unit test?

**Comment by rusefillc** [comment]
@mck1117 poke maybe this one is related to #2918

**Pull request merged**
