### PR TITLE
Avoid float -> int64 conversion

### PR DESCRIPTION
**Pull request by mck1117**

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 it says "conflicts" it also says "4 commits" as in "not 1 commit in a proper squash"

**Comment by mck1117** [comment]
no more conflict, and if it was just one commit, how could you cherry-pick smaller parts of it? why not just merge then?

**Comment by rusefillc** [comment]
my cherry picking is not honest GIT cherry picking - my cherry picking is IDEA IDE "apply selected changes" per-file picking

not merging because I am still trying to comprehend the changes

**Comment by mck1117** [comment]
at this point it's like 15 total characters worth of changes, so I'll let you do it by hand if you really want to 🙂

**Comment by rusefillc** [comment]
Please add code comments around USF2NT vs US2NT in efitime.h

**Comment by rusefillc** [comment]
kind of tempting to add "assert value duration below 10 seconds"

**Comment by rusefillc** [comment]
I've cherry picked all of this with some additional comments. Close?

**Comment by rusefillc** [comment]
@mck1117 please close, or maybe merge and close to confirm everything in master?

**Comment by mck1117** [comment]
confirmed as 0 files changed, shall close

**Pull request closed without merging**
