### PR TITLE
Chibios-Contrib for stm32

### PR DESCRIPTION
**Pull request by dron0gus**
Chibios-Contrib contains some useful stuff. Like HW CRC calculator driver for STM32.
Include it into build and add configs for STM32 chips

### CODE REVIEW

**Comment by mck1117** [comment]
is there a specific thing you wanted to add that's implemented in `ChibiOS-Contrib`?

**Comment by dron0gus** [comment]
> is there a specific thing you wanted to add that's implemented in `ChibiOS-Contrib`?
Yes. HW CRC calculation unit driver. Gives some boost over SW implementation on blocks > 300 bytes.

**Comment by mck1117** [comment]
I don't remember if it lets you configure the polynomial, does it?

**Comment by dron0gus** [comment]
CRC unit at F7 and H7 allow to configure CRC bit size and polynomial.
F407 and F247 do not.

**Pull request merged**
