### PR TITLE
Closed Loop Idle Ignition Timing small improvements

### PR DESCRIPTION
**Pull request by pchmura4**
For aggressively tuned CL Idle Timing in some cases it could have a harsh entry after Cranking Taper to Idle.
I would like to introduce a simple idea that can make this more subtle I think.
obraz

Also I think it would be nice to enable Integral term for having perfectly met target RPM without aggressive PD tuning, correct me if I'm wrong :)

Unfortunately it was not tested on real vehicle as for some reason all the builds with _PROJECT_BOARD=proteus_ option are ending up creating image for default F407... Will try it out as soon as I'll figure out how to build it properly

### CODE REVIEW

**Comment by rusefillc** [comment]
this https://github.com/rusefi/rusefi/pull/5635 PR shows 10 commits and this bothers my OCD just a bit. While rebase has risks it gives cleanest commit history

unit tests are not happy?

**Comment by pchmura4** [comment]
yes, you are right, unfortunately I have no access to test result what went wrong there, nor I can't reproduce it myself... I think we can just cancel that...

**Comment by rusefillc** [comment]
```
Not enough data for unittest_PressureRatio/4.logicdata
[       OK ] InjectorModel/FlowRateFixture.PressureRatio/4 (0 ms)
[----------] 5 tests from InjectorModel/FlowRateFixture (2 ms total)

[----------] Global test environment tear-down
[==========] 626 tests from 127 test suites ran. (1044 ms total)
[  PASSED  ] 625 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] idle_v2.timingPid

 1 FAILED TEST
All triggers exported to triggers.txt
Error: Process completed with exit code 255.
```

**Comment by rusefillc** [comment]
> Unfortunately it was not tested on real vehicle as for some reason all the builds with _PROJECT_BOARD=proteus_ option are ending up creating image for default F407... 

@pchmura4 https://github.com/rusefi/rusefi/issues/5225

**Pull request merged**
