### PR TITLE
Fix sensor mocking bug

### PR DESCRIPTION
**Pull request by mck1117**
Actually really reset the registry when you ask it to.

### CODE REVIEW

**Comment by rusefi** [comment]
how come tests did not reveal issue? do we need changes in tests?

**Comment by mck1117** [comment]
The issue was that state was leaking between tests.  Since the test run order isn't guaranteed, this one is pretty hard to test.  Let me see if I can come up with something, though.

**Comment by mck1117** [comment]
I suppose I can at least test that `resetRegistry` is really fully resetting it.

**Comment by rusefi** [comment]
unit tests have failed - reverting commit

[----------] Global test environment tear-down
[==========] 100 tests from 27 test cases ran. (34 ms total)
[  PASSED  ] 99 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SensorMocking.ResetWithResetRegistry

**Pull request merged**
