### PR TITLE
lua 5.4

### PR DESCRIPTION
**Pull request by mck1117**
not enabled on real hardware yet (but works), just loads a hardcoded script that prints out sequentially counting up integers

### CODE REVIEW

**Comment by rusefillc** [comment]
can we submodule or not for some reason?

plz add a unit test ideally

plz add a brief overview of integration points/approach into some .md file

love it

**Comment by mck1117** [comment]
The problem I saw with submodule was that the file `luaconf.h` is in the lua/src folder, and not really any way to replace it :(

**Comment by rusefillc** [comment]
can we have our own copy of that file and rely on order of includes?

**Comment by mck1117** [comment]
> rely on order of include durectories

I just tried it and unfortunately that doesn't work, since the compiler always looks in the current directory of the source file before checking the include path, and `lauconf.h` is in the same folder as most of the source c files.

**Comment by rusefillc** [comment]
we have to fork them and rename file on our fork

**Comment by rusefillc** [comment]
and reference our fork

**Comment by rusefillc** [comment]
like we do chibios

**Comment by rusefillc** [comment]
@mck1117 you have write access to https://github.com/rusefi/lua now

**Comment by mck1117** [comment]
fixes #2578

**Pull request merged**
