### PR TITLE
dead code

### PR DESCRIPTION
**Pull request by mck1117**

### CODE REVIEW

**Comment by rusefillc** [comment]
I see two unrelated changes here :(

Why kill ignMathCalculateAtIndex but not mapAveragingSchedulingAtIndex?

**Comment by rusefillc** [comment]
@mck1117 please articulate your arguments just for the sake of transparency.

**Comment by rusefillc** [comment]
@mck1117 poke

**Comment by mck1117** [comment]
> Why kill ignMathCalculateAtIndex but not mapAveragingSchedulingAtIndex?

Because I looked in the "experimental/broken" dialog in TS, and I *knew* that `ignMathCalculateAtIndex` didn't do anything.  So here it is.

**Pull request merged**
