### PR TITLE
https://github.com/rusefi/rusefi_documentation/issues/226

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by mck1117** [comment]
I am hesitant about this `LuaAdjustmentsLegacy`, because it makes it really difficult to cleanly reset the full lua adjustment state.

**Comment by rusefillc** [comment]
Absolutely, i shall clean this up really soon

**Comment by mck1117** [comment]
My concern is that RIGHT NOW there is a bug possible where your throttle sticks open. Let's at least fix that one.

**Comment by rusefillc** [comment]
i am not aware of that bug and you are not pointing at it. At the moment I have no specifics to move forward.

**Comment by rusefillc** [comment]
My name is Andrey. Today is June of 2022.

electronic_throttle_s has "luaAdjustment" since April of 2022. 

https://github.com/rusefi/rusefi/issues/4308 created

**Pull request merged**
