### PR TITLE
ETB error counter logic

### PR DESCRIPTION
**Pull request by mck1117**
- Each ETB only checks its own TPS
- Increment counter on rising edges, not on both edges
- Reset counter if something "weird" happens (ignition power cycle, autotune)
- Reorder logic so counter reset works
- Update test to check multiple cycles of good/bad TPS
- Update test to check that `etbErrorCode` changes correctly
- "jitter" -> "intermittent"

#4832

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 just shipped you x2 VAG pigtails and x2 Nissan pigtail

At the moment VAG ETB is the best way I know to reproduce the problem on the bench

**Comment by rusefillc** [comment]
I believe that master detects intermittent TPS while this PR seems to kill that feature. Let me make some evil picking and add a new test into master.

**Comment by mck1117** [comment]
> I believe that master detects intermittent TPS while this PR seems to kill that feature. Let me make some evil picking and add a new test into master.

wait a sec - this does absolutely count intermittent TPS

**Comment by rusefillc** [comment]
@mck1117 please _rebase_ in light of https://github.com/rusefi/rusefi/commit/405b23d6823fa287dbe0ebe1952cf09479cd5c3b

**Pull request merged**
