### PR TITLE
Update trigger_suzuki.cpp

### PR DESCRIPTION
**Pull request by EA11R**
https://forums.linkecu.com/topic/9105-k6a-trigger-setting/

I think the Sync edge is the opposite side (FALLING)

it has been tested on a car recently the car runs but keeps returning trigger error it does read correct rpm however?

it runs smoothly till it reaches a full cycle (CUTS IGNITION) then back to normal

however it gives a check engine light (TRIGGER ERR) each 720deg 

I will upload logs to rusefi online

### CODE REVIEW

**Comment by rusefillc** [comment]
@EA11R the description here is too vague and confusing 

1) are you experiencing any real like problems without the change? Please attach a log with problems without the chance 

2) is anuthing getting better with the change? Please qttach a log with the change

**Comment by EA11R** [comment]
https://rusefi.com/online/view.php?log=1415

**Comment by EA11R** [comment]
https://github.com/user-attachments/assets/08af0a39-9ae4-427a-b81f-5f2b44d44004

**Comment by rusefillc** [comment]
@EA11R please improve comment above. Need clarity if linked log is with or without change

**Comment by EA11R** [comment]
current log is without changes as is , I will attempt to build to build FW and try again tomorrow to see if it makes a difference but the trigger error either shows up at each 360 or 720? I think

**Comment by rusefillc** [comment]
@EA11R please note that unit test is failing / this PR is red. The modified code does not seem to be working.

I would like to propose an alternative approach. Please use something like https://www.ebay.com/itm/124238666414 to record a real life logic analyzer trace of the signal and share it with me.

**Comment by EA11R** [comment]
I have a logic analyzer, I can hook it hp directly to the conditioner pins and send a log file , however I can crank the wheel at hand speed and that could be inconsistent?

**Comment by EA11R** [comment]
[ea21rtrigger.zip](https://github.com/user-attachments/files/16568610/ea21rtrigger.zip)
heres some scopes from VR pin and another with VR wires reversed 
[wiresflipped.zip](https://github.com/user-attachments/files/16568616/wiresflipped.zip)

**Comment by EA11R** [comment]
image

Heres a known trigger GM 60/2/2/2 
Next to it

If I take a picture of both and overlay them would that be any help? To realize angles

**Comment by rusefillc** [comment]
> I have a logic analyzer, I can hook it hp directly to the conditioner pins and send a log file

please disable ignition
please cranking using starter
we can do two files:

* without ignition, starter cranking, with spark plugs in place
* without ignition, starter cranking, spark plugs removed to eliminate engine compression

**Comment by EA11R** [comment]
The car is with another person I will ask him to do it 

Even for me its impossible to get a good edge without having the engine to make a code 

, do you want a trigger scope log with the logic analyzer one?

**Comment by rusefillc** [comment]
@EA11R yes I want a logic analyzer snapshot file

**Comment by rusefillc** [comment]
@EA11R poke on logic analyzer file

**Comment by rusefillc** [comment]
looks abandoned, closing

**Comment by EA11R** [comment]
[ea21rlogic.zip](https://github.com/user-attachments/files/17799489/ea21rlogic.zip)
Logic 1.2.40 software capture

**Pull request closed without merging**
