### PR TITLE
icu trigger: do not crash on incorrect brainPin

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
add to white list

**Comment by rusefi** [comment]
do we have warning error generated inside the "startDigitalCapture"? Do we want to add code comment "error already reported" next to "return NULL"?

**Comment by dron0gus** [comment]
> do we have warning error generated inside the "startDigitalCapture"? Do we want to add code comment "error already reported" next to "return NULL"?

Yes. We have:
```
	ICUDriver *driver = getInputCaptureDriver(msg, brainPin);
	if (driver == NULL) {
		warning(CUSTOM_ERR_INVALID_INPUT_ICU_PIN, "w_not input pin");
		return NULL;
	}
```
inside addWaveAnalyzerDriver
Comment added.

**Pull request merged**
