### PR TITLE
experimenting with engine class binding

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by rusefillc** [comment]
https://github.com/gengyong/luaaa/issues/2 wow perfect timing

**Comment by rusefillc** [comment]
@gengyong 

input
```
t = Timer.new();
e =  Engine:getInstance();
```


```
2021-09-23_19_08_09_748: EngineState: confirmation_luareset:8
2021-09-23_19_08_09_831: EngineState: LUA loading script length: 228...
2021-09-23_19_08_09_831: EngineState: LUA ERROR loading script: [string "t = Timer.new();..."]:2: field 'getInstance' is not callable (a nil value)
2021-09-23_19_08_09_833: EngineState: LUA: Tearing down instance...
```
how comes getInstance is a field? what part is nil? One day I will know.

**Comment by rusefillc** [comment]
@mck1117 shall we kill this?

**Comment by mck1117** [comment]
sure

**Pull request closed without merging**
