### PR TITLE
Compute injection duration later in the pipeline

### PR DESCRIPTION
**Pull request by mck1117**
progress on #2044 

This moves the mass -> duration calculation much later so that:
- per-bank trim can be applied
- wall wetting math works correctly when fuel pressure varies (for the same mass, the pulse width could change, but that change shouldn't apply a wall wetting correction!)

### CODE REVIEW

**Comment by rusefillc** [comment]
poke @mck1117

**Comment by rusefillc** [comment]
@mck1117 what's the plan here :)

**Comment by mck1117** [comment]
The plan here is that PR hardware CI has caught a problem :)

**Comment by mck1117** [comment]
found the bug, ready to go!

**Pull request merged**
