### PR TITLE
Proteus HW CI test branch

### PR DESCRIPTION
**Pull request by rusefillc**
one real commit ago https://github.com/rusefi/rusefi/commit/17f508e158971115ab450a6f389cffa2eead6692 HW CI proteus is a success

with just a text file to reduce change of breakage Proteus HW CI is red. is that a platform glitch of some sort?

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 any chance you could poke the platform?

**Comment by rusefillc** [comment]
@chuckwagoncomputing does this look like platform issue to you? Looking for another seg of eyes

**Comment by chuckwagoncomputing** [comment]
I have no idea. Maybe try flashing the uploaded bin artifact to a Proteus and see if it all seems OK?

**Comment by rusefillc** [comment]
Sad status update: 
a) https://github.com/rusefi/rusefi/issues/5986
b) we have one green and one red of what I would be assume same exact execution?!

**Comment by rusefillc** [comment]
@chuckwagoncomputing @mck1117 weird:

on PRs with double-run it sometimes passes (or _always_ passes on first go?)

while on main branch with single GHA it reliably fails. that's an odd combination.

**Comment by rusefillc** [comment]
@chuckwagoncomputing back to that weirdness of one check green and one check red: artifact sizes are different and looks like one has OpenBLT while another one does not! and that's from what we expect is totally same repo state?

red has no signs of OpenBLT which is UNEXPECTED
https://github.com/rusefi/rusefi/actions/runs/7949122305/job/21699923278?pr=5977
image

green shows signs of expected OpenBLT
https://github.com/rusefi/rusefi/actions/runs/7949121995/job/21699922547?pr=5977
image

**Pull request closed without merging**
