### PR TITLE
hey it's 2022! they have ChibiOS 21

### PR DESCRIPTION
**Pull request by rusefillc**
ChibiOS 21

### CODE REVIEW

**Comment by rusefillc** [comment]
image

**Comment by rusefillc** [comment]
@mck1117 wanna take a turn?

**Comment by rusefillc** [comment]
image

**Comment by mck1117** [comment]
have we merged our custom chibios changes in to our 21 branch?

**Comment by rusefillc** [comment]
https://github.com/rusefi/ChibiOS/commits/stable_21.11.x.rusefi

**Comment by mck1117** [comment]
for example do we have https://github.com/rusefi/ChibiOS/commit/cf743886935c39cbf2ca711e54e9e64238da6e57 ?

**Comment by rusefillc** [comment]
@nmschulte :)

**Pull request closed without merging**
