### PR TITLE
save table config space, store lua script in config

### PR DESCRIPTION
**Pull request by mck1117**
- Remove some small unused blocks, consolidating at the end #1753
- Make many tables scaled int16 or uint16 instead of float (saves half the space!)
- Store Lua script (2.5k) at the end

### CODE REVIEW

**Comment by rusefillc** [comment]
we would need a changelog here

we would need to create a release before this super incompatible change

**Comment by mck1117** [comment]
super incompatible ish - revving the flash version does mean TS will be able to port across the format change

**Comment by mck1117** [comment]
Hmm, this is actually a huge hassle.  Let me try to improve the world a bit and come back to this.

**Comment by rusefillc** [comment]
I like improving the world :)

**Comment by mck1117** [comment]
see #2702

**Pull request closed without merging**
