### PR TITLE
broadcast button toggle counter #5514

### PR DESCRIPTION
**Pull request by andreika-git**

### CODE REVIEW

**Comment by rusefillc** [comment]
libfirmware change does not seem relevant please rebase in order to not have this as part of this PR or split PR

**Comment by rusefillc** [comment]
let's reduce code duplication please reuse https://github.com/rusefi/rusefi/commit/b2c8e06d1c9297b418efab682fcc93f717e61add or implement something similar

**Comment by andreika-git** [comment]
> let's reduce code duplication please reuse [b2c8e06](https://github.com/rusefi/rusefi/commit/b2c8e06d1c9297b418efab682fcc93f717e61add) or implement something similar

SwitchState doesn't seem to be currently used by any code, right? May I change it to suit our needs, then? For example, it uses pointers instead of storing the state and counter inside and doesn't have getters/setters.

**Comment by rusefillc** [comment]
@andreika-git да, это прототип его можно менять

**Pull request closed without merging**
