### PR TITLE
Fix #1492

### LINKED ISSUE #1492: code generator - reduce the gap between Windows and Linux
at the moment we have to manually sync gen_config.bat and gen_config.sh since all the parameters are hard-coded inside those platform-specific scripts

@ksmola got hit by that when .sh got outdated around firing order parameter

a proper fix would be to extract parameters into input file(s) so that one file could be modified and both scripts for both platforms would still work fine

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
All the parameters to be passed to java are now in gen_config.conf.
gen_config.bat just calls gen_config.sh.
It checks whether C:\cygwin or C:\cygwin64 exists. Are there any situation in which one of these would not be true?

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
Can one of the admins verify this patch? (meaning the author is not on the white list)

**Comment by rusefi** [comment]
add to whilelist

**Comment by rusefi** [comment]
at first glance it looks like we have to unrelated changes mixed here - I see GH actions which is one improvement and then something for gen_config which is a totally separate area? Please clarify if that's the case or not

two separate changes would have to be two separate PRs

**Comment by rusefi** [comment]
add to white list

**Comment by rusefi** [comment]
it looks like the root cause of the issue is the fact that you are PRing your master

it looks like a proper process would be to have branches with one change per one branch. this way you PR your specific dev branch and you can keep other activities on separate branches.

**Comment by chuckwagoncomputing** [comment]
Yep, that's what I did. I'll close this and start over.

**Pull request closed without merging**
