### PR TITLE
Test bench: implement injector test for dead time calculation

### PR DESCRIPTION
**Pull request by dron0gus**
This is preparation to implement TS dialog where user can define on time, off time and iteration count for injector test.

### CODE REVIEW

**Comment by mck1117** [comment]
this is just an alternative to using rusEFI console command for the same job?

**Comment by dron0gus** [comment]
> this is just an alternative to using rusEFI console command for the same job?

Yes. Just to do the same job using GUI.

**Comment by mck1117** [comment]
I think it might be possible to have a pc variable that sets part of the bytes sent for bench test command, might be worth investigating

**Comment by dron0gus** [comment]
> I think it might be possible to have a pc variable that sets part of the bytes sent for bench test command, might be worth investigating

Need to dig into other's ECU ini files.
But documentation says nothing about this http://tunerstudio.com/index.php/support/manuals/tsdevmanuals/80-command-buttons

**Comment by mck1117** [comment]
> But documentation says nothing about this

yeaaaah, the documentation doesn't say a lot of things....

**Comment by mck1117** [comment]
Had a look at an MS3 ini, and nope, it just sets normal config fields on the ECU then sends a plain (constant) "do the thing" bench test command.

**Comment by rusefillc** [comment]
@dron0gus shall we merge this or do you plan changed or else?

**Pull request merged**
