### PR TITLE
Spell checked and hopefully merge fixed

### PR DESCRIPTION
**Pull request by OrchardPerformance**

### CODE REVIEW

**Comment by rusefi** [comment]
Can one of the admins verify this patch?

**Comment by rusefi** [comment]
@mck1117 @andreika-git do we want 24 or 48 hours for review?

**Comment by OrchardPerformance** [comment]
Fine to review at your leisure, its only the same changes in the last PR but without the problems.

**Comment by rusefi** [comment]
I believe I've resolved merge conflict & merged to the best of my abilities. See https://github.com/rusefi/rusefi/commit/ed38c63b8e8013f9e4e8c05ac94df000e527732b

**Pull request closed without merging**
