### PR TITLE
Update rusefi_f407-discovery.ini with 3D maps

### PR DESCRIPTION
**Pull request by zed65**
Added dedicated 3D maps

### CODE REVIEW

**Comment by zed65** [comment]
3dTuning

**Comment by rusefillc** [comment]
@zed65 ohh you mean all the way top level maps. I am hesitant to add, I am not convinced that it's worth the cost of screen "real estate". Somewhere on a narrow screen that new button would be a major problem for someone

@ElDominio do you have an opinion?

**Comment by zed65** [comment]
I understand, but what if we add them under "Fuel", my point is to get gauges and histogram to the left of the map

**Comment by rusefillc** [comment]
> my point is to get gauges and histogram to the left of the map

that I would happily merge! Still a bit confused what does that have to do with 3D since 3D and flat table seems to be separate unrelated switch? anyway please create new or update this PR?

**Comment by ElDominio** [comment]
But Tunerstudio generates 3d maps if you click the 3d map checkbox?

**Comment by zed65** [comment]
Maybe I'm missing something but I'm used to be able to maximize the tune window and still have your favorite gauges there
Anyway I think I made the changes in this PR (I'm totally new to this fork and PR thing :))
3dTuning4

**Pull request closed without merging**
