### PR TITLE
Engine Sniffer into TS data logs fix #4535

### LINKED ISSUE #4535: Engine Sniffer into TS data logs
We have amazing data rate, let's dump injector and coil state right into data logs

### PR DESCRIPTION
**Pull request by rusefillc**
image

We can see logic state of coils and injectors in MLV

I belive that would help troubleshoot stuff like #4477

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 polymorphism or not?

@mck1117 horrible switch with bits or byte array?

**Comment by mck1117** [comment]
wait, what? what's the goal here?

**Comment by rusefillc** [comment]
@mck1117 description updated

**Comment by mck1117** [comment]
what does `polymorphism or not` mean?

**Comment by rusefillc** [comment]
@mck1117 are concurned about making setHigh/setLow virtual and ending up with runtime lookup tables?

**Comment by mck1117** [comment]
> horrible switch with bits or byte array?

As I think I mentioned once before, this is _technically_ unsafe (BUT). Bit operations aren't atomic on any architecture I know of (you have to read, modify, write), while operations to different bytes (even adjacent bytes) are.  However, this should be OK since everything touching these bits (injection, ignition) are running at the same interrupt priority, plus it's not "critical" data but instead "nice to have" data.

I think byte array is overkill, and unfortunately C++ doesn't let you index arrays of bits like it does an array of bytes, so switch it is.

**Comment by mck1117** [comment]
> are concurned about making setHigh/setLow virtual and ending up with runtime lookup tables?

They may not need to be virtual at all. Everyone that calls these is calling an `InjectorOutputPin` or `InjectorOutputPin`, not a `NamedOutputPin`. So we could add `setHighAndReport` or something for injection/ignition to call that have this extra reporting bolted on, with no virtual call required.

**Comment by rusefillc** [comment]
@mck1117 obviously virtual could be avoided easily

question is if we WANT virtual for OOP or else, or if we want to AVOID virtual for CPU costs or else.

**Pull request merged**
