### PR TITLE
Refactoring: limp manager handling of engine stop

### PR DESCRIPTION
**Pull request by mck1117**
related to #3070

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 it's red

**Comment by mck1117** [comment]
yeah I know

**Comment by rusefillc** [comment]
@mck1117 poke poke this one is an important one

also this one has to go on CHANGELOG

**Comment by rusefillc** [comment]
@mck1117 are we still interested in this PR?

**Comment by rusefillc** [comment]
@mck1117

**Comment by rusefillc** [comment]
looks like we have progress here, this PR is now green at least!

@andreika-git shall I merge or not?

**Comment by andreika-git** [comment]
We did some important changes to the master.
It seems that we need to review this PR before merging. The situation is not THAT simple.

**Comment by mck1117** [comment]
Let's wait for #3636

**Comment by rusefillc** [comment]
@mck1117 we now have #3636

**Comment by rusefillc** [comment]
Merged as #3879

**Pull request closed without merging**
