### PR TITLE
kill dead time type

### PR DESCRIPTION
**Pull request by mck1117**

### CODE REVIEW

**Comment by rusefi** [comment]
We've been here before with removal of questionable fratures. Lets just ignore them instead.

**Comment by mck1117** [comment]
That's not a convincing reason to keep it.

Do you have an actually convincing reason to keep a 1% complete feature that was abandoned 3 years ago?

There's no way to deal with technical debt other than actually growing up and facing it.

**Comment by rusefi** [comment]
We have a difference of opinions here. I am not interested to drbate this issues where you definitely have a legit point of view.

**Comment by mck1117** [comment]
> you definitely have a legit point of view

Great, so we agree! Why not merge then?

**Pull request closed without merging**
