### PR TITLE
Move slow ADC to thread #630

### LINKED ISSUE #630: migrate slow ADC to software timer so that TIM8 is also available for input capture
We would like to change
#define STM32_ICU_USE_TIM8                  FALSE
to
#define STM32_ICU_USE_TIM8                  FALSE
which means that

#define STM32_PWM_USE_TIM8                  TRUE
should be changed to
#define STM32_PWM_USE_TIM8                  FALSE

which means that 
#define EFI_INTERNAL_SLOW_ADC_PWM	&PWMD8
has to go

### PR DESCRIPTION
**Pull request by mck1117**
Move the slow ADC to its own thread.  We were previously using a hardware timer, which had a few problems.
1. It tied up the hardware timer
2. It didn't participate in the OS's priority system - so it could stomp other work being done.
3. Wasn't very portable.  Required a dedicated hardware timer, but now only relies on core OS functionality to run the ADC.

This closes #630.

### CODE REVIEW

**Comment by rusefi** [comment]
this is related to #630

**Comment by rusefi** [comment]
Oh! That's a great change!

How easy is it for you to test on a real vehicle?

**Comment by mck1117** [comment]
Might be a little difficult to test on a real vehicle for a few weeks...

image

**Comment by mck1117** [comment]
This code has now been used on a running, driving car!

**Pull request merged**
