### PR TITLE
OpenBLT will accept connections during the start if the firmware is already present

### PR DESCRIPTION
**Pull request by andreika-git**
https://github.com/rusefi/rusefi/issues/6246

Tested on small-can-board

Also tested on Proteus-F7 (except for https://github.com/rusefi/rusefi/issues/6247)

### CODE REVIEW

**Comment by mck1117** [comment]
so this increases the boot time by 500ms?

**Comment by andreika-git** [comment]
The default 0.5 sec delay is usually NOT ENOUGH to connect via USB during the normal boot mode, but 1 second is enough.
We should decide is 1 sec will be the new default value. Also need to test CAN connection.

**Comment by andreika-git** [comment]
> so this increases the boot time by 500ms?

Yes, otherwise the bootloader is useless as a recovery tool with failed firmware.

**Comment by andreika-git** [comment]
I've tested BOOT_BACKDOOR_ENTRY_TIMEOUT_MS=0 on 2chan. It doesn't work as expected.
We cannot skip BootTask() if BOOT_BACKDOOR_ENTRY_TIMEOUT_MS==0, because we still need to use the bootloader to update the firmware. We cannot even call it only for stayInBootloader==true, because there's a case when there's no firmware (only bootloader), and we cannot detect it easily, except for calling CpuStartUserProgram() and BootTask() repeatedly.

**Pull request merged**
