### PR TITLE
Link was not Redirecting to Proper File

### PR DESCRIPTION
**Pull request by vivekBoii**
Update README.md
changed link

### CODE REVIEW

**Comment by rusefillc** [comment]
Thank you for pointing at the problem! I made a slightly better edit https://github.com/rusefi/rusefi/commit/d60c7a5c01d94e9923d7c0470df1b1d69ff847f0

**Comment by vivekBoii** [comment]
Brother , I was doing it for Hactoberfest If you have stated me I have done it . Sorry , If you feel bad but I am new at opensource and these merged PR is motivation for me to keep contributing

**Comment by rusefillc** [comment]
Please see it from my point I have limited resource to guide. Please compare your version of the change and my version of the change.

**Comment by mck1117** [comment]
@vivekBoii please make a positive change if you're going to show up to a new project and make a doc change. Linking to a particular revision of a file that might change in the future is NOT a positive change.

**Pull request closed without merging**
