### PR TITLE
RusEFI is green: put cpu in standby in idle

### PR DESCRIPTION
**Pull request by dron0gus**
For MRE:
This drops consumption from 0.18A@12V to 0.17A@12V.
Sorry, my lab DC power supply has 0.01A resolution.

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 @andreika-git do we want this more globally?

**Comment by mck1117** [comment]
datasheet on an F4 says that run vs. sleep is about 90 vs 60mA, so that math sounds about right

**Comment by mck1117** [comment]
I can't find the difference in interrupt latency if asleep vs. running, @dron0gus do you know?

**Comment by dron0gus** [comment]
@mck1117 look like additional 6 CPU clocks are needed to exit SLEEP mode.
Screenshot from 2021-02-13 23-23-57

**Comment by mck1117** [comment]
And standard is 12 cycles for an interrupt? An extra 35ns seems like no problem at all.

**Comment by rusefillc** [comment]
if we like it, this should be universal option not just MRE

**Comment by mck1117** [comment]
Agree, we should just put it in chconf_common or something

**Comment by dron0gus** [comment]
chcore_v6m.h and chcore_v7m.h contain port_wait_for_interrupt() implementation where CORTEX_ENABLE_WFI_IDLE is used.
Both do not include any config files.
Actually both do not include any other file.
So defining this option through mk/Makefile files and DDEFS is the only option I see.

**Comment by mck1117** [comment]
Ew, that's gross.  I guess in the makefile it goes!

**Comment by dron0gus** [comment]
Ok. I was wrong. chconf.h is included prior to chcore_v6m.h and chcore_v7m.h and supposed to be used for this option.
Will update PR.

**Comment by mck1117** [comment]
ugh I hate it when headers don't explicitly include all their dependencies

**Comment by dron0gus** [comment]
ch.h is meta-include that combines everything together.

**Pull request merged**
