### PR TITLE
Openblt to dfu jump fixed

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by rusefillc** [comment]
@dron0gus this is interesting enough to provide a description pretty please :)

**Comment by dron0gus** [comment]
@rusefillc copy-paste same check and jump code that is used in main RE app.
OpenBLT is executed first so check 0xDEADBEEF as soon as possible.

**Comment by dron0gus** [comment]
Mostly re-use and some copy-paste (where reuse is not possible)

**Comment by rusefillc** [comment]
oh so that fixes #4230

**Pull request merged**
