### PR TITLE
add proteus hw ci yaml

### PR DESCRIPTION
**Pull request by mck1117**
Now there's a machine for this to run on!

### CODE REVIEW

**Comment by mck1117** [comment]
Need to plug in the ECU to the build machine, but I'm out of outlets on the power strip :upside_down_face:

**Comment by mck1117** [comment]
this PR has now required a trip to my local Ikea

**Comment by rusefillc** [comment]
hehe

**Comment by mck1117** [comment]
And yes, I drove a Volvo station wagon to Ikea as you're supposed to do

**Comment by mck1117** [comment]
image

:tada::tada::tada:

**Pull request merged**
