### PR TITLE
WIP: add Benelli Walbro

### PR DESCRIPTION
**Pull request by mi-hol**
WIP: expected are errors because local development environment was not setup (see https://github.com/rusefi/rusefi_documentation/issues/377#issuecomment-1381758543)

### CODE REVIEW

**Comment by mck1117** [comment]
we shouldn't be including random changes to vscode config files

**Comment by rusefillc** [comment]
hellen means there is a kicad project, please paste URL or screenshot of kicad project?

I wonder if this is ONLY about connector mapping? that case this PR should have only two files and NOT into hellen folder?

**Comment by mi-hol** [comment]
> this is ONLY about connector mapping

correct, but the instructions are not clear yet to avoid issues (as mentioned in https://github.com/rusefi/rusefi_documentation/issues/377)

**Comment by mi-hol** [comment]
> his PR should have only two files and NOT into hellen folder

@rusefillc could you please name the 2 files and the correct folder name, so I can create a correct PR?

**Comment by rusefillc** [comment]
firmware/config/boards/Benelli_Walbro/connectors/Benelli_Walbro.jpg
firmware/config/boards/Benelli_Walbro/connectors/Benelli_Walbro.yaml

**Pull request closed without merging**
