### PR TITLE
EGT/max3185x fixes

### PR DESCRIPTION
**Pull request by dron0gus**
Tested with max31856 only.
@zed65 need your help testing with max31855, please.

### CODE REVIEW

**Comment by zed65** [comment]
Nope, the needle just sits at 0 all the time.
egt2

**Comment by rusefillc** [comment]
@zed65 we have helpful ``egtinfo`` command in rusEFI console - please paste output

**Comment by zed65** [comment]
2024-03-10_21_05_37_602: EngineState: spi 1=Yes/2=Yes/3=Yes/4=No
2024-03-10_21_05_37_602: EngineState: EGT spi: 2
2024-03-10_21_05_37_602: EngineState: 0 ETG @ PE4
2024-03-10_21_05_37_602: EngineState: confirmation_egtinfo:7

**Comment by rusefillc** [comment]
@zed65 my bad I should have also asked for ``egtread`` command as well, it has more cool info

**Comment by zed65** [comment]
2024-03-11_00_05_24_887: EngineState: Reading egt
2024-03-11_00_05_24_887: EngineState: egt: code=4 (no reply)
2024-03-11_00_05_24_887: EngineState: confirmation_egtread:7

**Pull request merged**
