### PR TITLE
rpm rate of change

### PR DESCRIPTION
**Pull request by mck1117**
repurpose old dRPM as a usable unit of RPM/s

### CODE REVIEW

**Comment by mck1117** [comment]
also related to #927 - this change computes accurate dRpm/dT only when we update RPM

**Comment by mck1117** [comment]
image

Red is the new channel, green is as-computed from instant RPM in MLV after the fact.  Perfect match, except the new channel is noise free because it only updates on RPM change!

**Comment by rusefillc** [comment]
@mck1117 I believe we have a problem here

image

```
    [junit] 2021-01-03_10_18_16_797<EOT>: AUTOTEST nextChart() in 547
    [junit] ------------- ---------------- ---------------
    [junit] 
    [junit] Testcase: testMazdaProtege took 18,77 sec
    [junit] 	FAILED
    [junit] Not true: ProtegeLX cranking
    [junit] junit.framework.AssertionFailedError: Not true: ProtegeLX cranking
    [junit] 	at com.rusefi.TestingUtils.assertTrue(TestingUtils.java:34)
    [junit] 	at com.rusefi.FunctionalTest.assertWaveNotNull(FunctionalTest.java:477)
    [junit] 	at com.rusefi.FunctionalTest.testMazdaProtege(FunctionalTest.java:281)
    [junit] 
    [junit] Testcase: testCamaro took 5,563 sec
    [junit] Testcase: testFordAspire took 45,83 sec
    [junit] Testcase: testRevLimiter took 8,641 sec
    [junit] Testcase: testSachs took 5,688 sec
    [junit] Testcase: testFord6 took 6,782 sec
    [junit] Testcase: testCustomEngine took 5,469 s
```

**Comment by mck1117** [comment]
yes, something is indeed funky.  Unclear exactly if it's related to this change, as nobody actually reads the modified channel, other than tunerstudio, but the timing certainly suggests that it is related.

**Pull request merged**
