### PR TITLE
Openblt proteus F7

### PR DESCRIPTION
**Pull request by rusefillc**
Let's give it another try!

### CODE REVIEW

**Comment by rusefillc** [comment]
@mck1117 what's the difference between F4 and F7 proteus builds? i am confused about .ini MSD options and where are those defined

**Comment by mck1117** [comment]
> @mck1117 what's the difference between F4 and F7 proteus builds? i am confused about .ini MSD options and where are those defined

image

EFI_EMBED_INI_MSD is disabled on all F7.

**Comment by rusefillc** [comment]
```
[build-firmware (proteus_f7)](https://github.com/rusefi/rusefi/runs/6443962676?check_suite_focus=true#logs)
Compiling rusefi.cpp
Compiling main.cpp
Linking build/rusefi.elf
/home/runner/work/rusefi/rusefi/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: build/rusefi.elf section `.rodata' will not fit in region `flash0'
/home/runner/work/rusefi/rusefi/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: region `flash0' overflowed by 13984 bytes
collect2: error: ld returned 1 exit status
make: *** [ChibiOS/os/common/startup/ARMCMx/compilers/GCC/mk/rules.mk:217: build/rusefi.elf] Error 1
ERROR invoking compile_proteus_f7.sh
Error: Process completed with exit code 1.
```

**Comment by rusefillc** [comment]
```
Linking build/rusefi.elf
/home/runner/work/rusefi/rusefi/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: build/rusefi.elf section `.rodata' will not fit in region `flash0'
/home/runner/work/rusefi/rusefi/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: region `flash0' overflowed by 10288 bytes
collect2: error: ld returned 1 exit status
make: *** [ChibiOS/os/common/startup/ARMCMx/compilers/GCC/mk/rules.mk:217: build/rusefi.elf] Error 1
```

**Pull request closed without merging**
