### PR TITLE
TinerStudio: no need to have 3s timeout, 300mS is ok.

### PR DESCRIPTION
**Pull request by dron0gus**
This allows faster detection of device disconnect and faster recovery

### CODE REVIEW

**Comment by dron0gus** [comment]
Tested on MRE with F407 - no disconnect on "Burn" with 300mS timeout.

**Review by mck1117 — CHANGES_REQUESTED** [review]
I'll ask phil what this parameter actually does, let's hold a bit for this one

**Comment by dron0gus** [comment]
I assume this is timeout that is used durin read call on serial device:

```
7/20/22 5:21:25 PM :Debug: Real OchDelay for SVX-002: 0, timeout=300
7/20/22 5:21:25 PM :Time: 0:10.157: SENT 11 bytes, 11 bytes
x00 x05 x4F x00 x00 xF4 x01 x1B x56 x2C xAA                           ..O.....V,.

Time: 0:13.158: READ Timout after 0 bytes, Expected:3, actual read:0 Raw buffer
7/20/22 5:21:28 PM :Debug: Comm Exception Caught: Timeout after:3001ms. requested timeout:3000, Expected bytes:3, bytes read:0
Jul 20, 2022 5:21:28 PM y.u run
WARNING: Comm Timeout Caught
U.b: Timeout after:3001ms. requested timeout:3000, Expected bytes:3, bytes read:0
	at y.t.a(Unknown Source)
	at F.J.b(Unknown Source)
	at F.J.a(Unknown Source)
	at F.J.b(Unknown Source)
	at F.J.z(Unknown Source)
	at y.t.e(Unknown Source)
	at y.u.run(Unknown Source)
```

**Comment by rusefillc** [comment]
@dron0gus can we measure actual F407 or F42x burn time?

**Comment by dron0gus** [comment]
This really cause reconnect on devices with single bank flash.
We ether should set different timeout for different devices, or keep it as is.

**Comment by rusefillc** [comment]
We can easilty have this configurable, let me make this a bit configurable

**Pull request closed without merging**
