### PR TITLE
move hooks in to common chconf.h

### PR DESCRIPTION
**Pull request by mck1117**
digestible pieces of #1010

### CODE REVIEW

**Comment by mck1117** [comment]
(don't worry, writing docs while this builds)

**Comment by rusefi** [comment]
@mck1117 not green?

**Comment by mck1117** [comment]
correct, not green, I'll comment when it's ready

**Comment by mck1117** [comment]
Ok, pending some more green check marks, this should be good to go! Kinetis `chconf.h` was a bit stale, but now that it's up to date with the others, things look good.

**Pull request merged**
