### PR TITLE
Tweak firmware Makefile, scripting

### PR DESCRIPTION
**Pull request by nmschulte**
a la #4794

### CODE REVIEW

**Comment by rusefillc** [comment]
please rebase to make this PR green

also I have no idea what does it do? diff shows massive code formatting

**Comment by rusefillc** [comment]
just cherry-picked two commits I could understand

**Comment by nmschulte** [comment]
@rusefillc it looks like you cherry-picked commits from the branch changing simulator (vs this one for firmware): #4794 

The meat of the changes (similar in both, but here for firmware) are:
- 49011362f699998343e753852f1509eb733f0e08 -- ensure that any user specified `CC`/`CPPC` (GCC compilers) are retained/used for the linker and other programs
- 41c5e22dbaefda2cf9e03791e6dd74ed78a9e164 -- `*compile*.sh` scripts pass arguments through to make, to e.g. allow setting `CC`/`CPPC` and compile defs

The change about indentation is to normalize things, and chooses spaces vs tabs because Makefiles interpret tabs vs spaces especially: `$(info ...)` lines for example will be interpreted as recipes if they begin with tabs, so it's not so simple to indent everything with tabs in Makefiles (here in rusEFI).

**Comment by rusefillc** [comment]
@nmschulte thank you! Please rebase just to get a nice green PR, also at least one of the commits should already be in master

**Pull request merged**
