### PR TITLE
Hellen mcu module detector (experimental)

### PR DESCRIPTION
**Pull request by andreika-git**
Currently tested only on Hellen81a (176-pin mcu) and Hellen72b (176-pin mcu).
Needs more testing.

### CODE REVIEW

**Comment by mck1117** [comment]
Can we put this code in a more hellen-specific place?

**Comment by andreika-git** [comment]
> Can we put this code in a more hellen-specific place?

Currently we don't have a common source file for all Hellen boards (we have only 'meta' h-file). Other Hellen-specific functions like setHellen144LedPins() were already inside custom_engine.cpp by Andrey, and I just added another one.

**Comment by rusefillc** [comment]
I have hellen88bmw at my place which is a 144 unit, it was properly detected as 144

```
2022-01-08_19_59_55_415: EngineState: Hellen board pin states = 0 1
2022-01-08_19_59_55_415: EngineState: * Hellen 144-pin mcu detected!
2022-01-08_19_59_55_415: EngineState: led: comm status on PE7

```

**Comment by rusefillc** [comment]
@andreika-git @mck1117 we now have new cpp file for common hellen-specific stuff https://github.com/rusefi/rusefi/commit/212687dd103441fc0fa2f6722cbd4589af798246

**Comment by rusefillc** [comment]
Let's use GH official "draft" feature for simplicity. As is I am super confused if I am supposed to merge this PR or not.

please remove "[DRAFT]" please mark draft or not, please tell me to merge or not merge. I am amazing at following simple instructions :)

**Comment by andreika-git** [comment]
The code seems to be harmless. The quesion is if it really works on all Hellen boards (whether it's robust enough). Maybe we should ask the community to help us test the code. And IMHO the best way to do this - is to merge :) If the code doesn't work properly, then... well, we're free to improve it or remove later...

**Comment by mck1117** [comment]
Now how about a hellen.mk so we don't have to touch every board for common Hellenic things...

**Pull request merged**
