### PR TITLE
Cypress CI

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
There's an error in the build, but I don't think it's my problem(?)

### CODE REVIEW

**Comment by rusefillc** [comment]
weird, it did compile for me locally. can you make clean and invoke cypress .sh lo CV ally does it complie for you?

**Comment by chuckwagoncomputing** [comment]
nope, same error.

**Comment by chuckwagoncomputing** [comment]
compile-cypress.sh fails on master too.

**Comment by rusefillc** [comment]
image

**Comment by rusefillc** [comment]
i.e. it looks to compile on Windows for me

**Pull request merged**
