### PR TITLE
schedule ignition charge by angle instead of tooth

### PR DESCRIPTION
**Pull request by mck1117**
Like #4208, but for both the dwell start and spark firing.

progress to #4195 

~probably related to #4477~ nope
probably related to #4421

### CODE REVIEW

**Comment by rusefillc** [comment]
https://github.com/rusefi/ChibiOS/pull/21

**Comment by mck1117** [comment]
> [rusefi/ChibiOS#21](https://github.com/rusefi/ChibiOS/pull/21)

huh?

**Comment by mck1117** [comment]
Looks good to me.

**Comment by rusefillc** [comment]
Nice, nice :)

**Pull request merged**
