### PR TITLE
generated for pt2001

### PR DESCRIPTION
**Pull request by mck1117**

### CODE REVIEW

**Comment by rusefillc** [comment]
please clarify if this code is compiled from https://github.com/rusefi/rusefi/tree/master/firmware/hw_layer/mc33816/rusefi source code

**Comment by mck1117** [comment]
this code came from @NOx-z, he's going to follow this up with the matching source

**Comment by rusefillc** [comment]
@NOx-z @mck1117 any progress on the source code?

**Comment by rusefillc** [comment]
@NOx-z poke?

**Comment by mck1117** [comment]
oops, didn't mean to delete the branch :joy:

**Comment by rusefillc** [comment]
@NOx-z @mck1117 bump

**Comment by mck1117** [comment]
this can go now

**Pull request merged**
