### PR TITLE
Tle8888 big update 1

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by mck1117** [comment]
This will require a corresponding update to `mapping.yaml` for microRusefi, and an increment to `FLASH_DATA_VERSION`.  With that, TS will properly help the upgrade happen.

**Comment by dron0gus** [comment]
mapping.yaml is updated.
I'll update `FLASH_DATA_VERSION` when code will be tested and ready for merge.
Someone with MRE on real car is welcomed to test this code. With last updates driver should handle TLE8888 undervoltage reset. Of so we can remove some dirty hacks.

**Comment by dron0gus** [comment]
Now with stepper support!

**Comment by rusefillc** [comment]
```
2020-10-22_21_16_53_466: EngineState: confirmation_pins:4
2020-10-22_21_16_53_466: EngineState: pin PA0: CLT
2020-10-22_21_16_53_467: EngineState: pin PA1: IAT
2020-10-22_21_16_53_467: EngineState: pin PA2: AUX Temp 1
2020-10-22_21_16_53_467: EngineState: pin PA3: AUX Temp 2
2020-10-22_21_16_53_467: EngineState: pin PA4: Injector 7
2020-10-22_21_16_53_467: EngineState: pin PA5: Cam
2020-10-22_21_16_53_467: EngineState: pin PA6: AFR
2020-10-22_21_16_53_467: EngineState: pin PA7: MAP
2020-10-22_21_16_53_467: EngineState: pin PA8: ETB Dir 1
2020-10-22_21_16_53_467: EngineState: pin PA11: USB DM
2020-10-22_21_16_53_468: EngineState: pin PA12: USB DP
2020-10-22_21_16_53_468: EngineState: pin PB0: Injector 9
2020-10-22_21_16_53_468: EngineState: pin PB1: Injector 8
2020-10-22_21_16_53_468: EngineState: pin PB3: SPI clock
2020-10-22_21_16_53_468: EngineState: pin PB4: SPI master in 
2020-10-22_21_16_53_468: EngineState: pin PB5: SPI master out
2020-10-22_21_16_53_468: EngineState: pin PB6: CAN TX
2020-10-22_21_16_53_468: EngineState: pin PB9: SD CS
2020-10-22_21_16_53_468: EngineState: pin PB10: console TX
2020-10-22_21_16_53_468: EngineState: pin PB11: console RX
2020-10-22_21_16_53_469: EngineState: pin PB12: CAN RX
2020-10-22_21_16_53_469: EngineState: pin PC0: MAF
2020-10-22_21_16_53_470: EngineState: pin PC1: VBatt
2020-10-22_21_16_53_470: EngineState: pin PC3: TPS 1 Primary
2020-10-22_21_16_53_470: EngineState: pin PC4: Injector 10
2020-10-22_21_16_53_470: EngineState: pin PC6: Trigger #1
2020-10-22_21_16_53_471: EngineState: pin PC7: ETB Enable
2020-10-22_21_16_53_471: EngineState: pin PC8: ETB Disable
2020-10-22_21_16_53_471: EngineState: pin PC10: SPI clock
2020-10-22_21_16_53_471: EngineState: pin PC11: SPI master in 
2020-10-22_21_16_53_472: EngineState: pin PC12: SPI master out
2020-10-22_21_16_53_472: EngineState: pin PD1: Coil 3
2020-10-22_21_16_53_472: EngineState: pin PD2: Coil 4
2020-10-22_21_16_53_472: EngineState: pin PD3: Coil 5
2020-10-22_21_16_53_472: EngineState: pin PD4: Coil 6
2020-10-22_21_16_53_476: EngineState: pin PD5: tle8888 CS
2020-10-22_21_16_53_476: EngineState: pin PD6: Coil 1
2020-10-22_21_16_53_477: EngineState: pin PD7: Coil 2
2020-10-22_21_16_53_477: EngineState: pin PD10: tle8888 IGN EN
2020-10-22_21_16_53_477: EngineState: pin PD11: tle8888 INJ EN
2020-10-22_21_16_53_478: EngineState: pin PE1: led: warning status
2020-10-22_21_16_53_478: EngineState: pin PE2: led: comm status
2020-10-22_21_16_53_478: EngineState: pin PE3: led: CRITICAL status
2020-10-22_21_16_53_478: EngineState: pin PE4: led: running status
2020-10-22_21_16_53_478: EngineState: pin PE7: tle8888 DIRECT IO
2020-10-22_21_16_53_479: EngineState: pin PE8: tle8888 DIRECT IO
2020-10-22_21_16_53_479: EngineState: pin PE9: tle8888 DIRECT IO
2020-10-22_21_16_53_479: EngineState: pin PE10: tle8888 DIRECT IO
2020-10-22_21_16_53_480: EngineState: pin PE11: tle8888 DIRECT IO
2020-10-22_21_16_53_480: EngineState: pin PE12: tle8888 DIRECT IO
2020-10-22_21_16_53_480: EngineState: pin PE13: tle8888 DIRECT IO
2020-10-22_21_16_53_480: EngineState: pin PE14: tle8888 DIRECT IO
2020-10-22_21_16_53_480: EngineState: ext TLE8888.INJ1: Injector 6 diagnostic: Ok
2020-10-22_21_16_53_481: EngineState: ext TLE8888.INJ2: Injector 5 diagnostic: Ok
2020-10-22_21_16_53_481: EngineState: ext TLE8888.INJ3: Injector 4 diagnostic: Ok
2020-10-22_21_16_53_481: EngineState: ext TLE8888.INJ4: Injector 3 diagnostic: Ok
2020-10-22_21_16_53_481: EngineState: ext TLE8888.OUT5: Injector 2 diagnostic: Ok
2020-10-22_21_16_53_482: EngineState: ext TLE8888.OUT6: Injector 1 diagnostic: Ok
2020-10-22_21_16_53_482: EngineState: ext TLE8888.OUT7: free diagnostic: open_load 
2020-10-22_21_16_53_483: EngineState: ext TLE8888.OUT8: free diagnostic: open_load 
2020-10-22_21_16_53_483: EngineState: ext TLE8888.OUT9: free diagnostic: open_load 
2020-10-22_21_16_53_483: EngineState: ext TLE8888.OUT10: Injector 12 diagnostic: Ok
2020-10-22_21_16_53_483: EngineState: ext TLE8888.OUT11: Coil 7 diagnostic: Ok
2020-10-22_21_16_53_483: EngineState: ext TLE8888.OUT12: Coil 8 diagnostic: Ok
2020-10-22_21_16_53_483: EngineState: ext TLE8888.OUT13: Injector 11 diagnostic: Ok
2020-10-22_21_16_53_484: EngineState: ext TLE8888.OUT14: free diagnostic: open_load 
2020-10-22_21_16_53_484: EngineState: ext TLE8888.OUT15: free diagnostic: open_load 
2020-10-22_21_16_53_484: EngineState: ext TLE8888.OUT16: free diagnostic: open_load 
2020-10-22_21_16_53_484: EngineState: ext TLE8888.OUT17: free diagnostic: open_load 
2020-10-22_21_16_53_485: EngineState: ext TLE8888.OUT18: free diagnostic: open_load 
2020-10-22_21_16_53_486: EngineState: ext TLE8888.OUT19: free diagnostic: open_load 
2020-10-22_21_16_53_486: EngineState: ext TLE8888.OUT20: free diagnostic: open_load 
2020-10-22_21_16_53_486: EngineState: ext TLE8888.OUT21: Coil 9 diagnostic: Ok
2020-10-22_21_16_53_490: EngineState: ext TLE8888.OUT22: Coil 10 diagnostic: Ok
2020-10-22_21_16_53_490: EngineState: ext TLE8888.OUT23: Coil 11 diagnostic: Ok
2020-10-22_21_16_53_490: EngineState: ext TLE8888.OUT24: Coil 12 diagnostic: Ok
2020-10-22_21_16_53_491: EngineState: ext TLE8888.IGN1: free diagnostic: Ok
2020-10-22_21_16_53_491: EngineState: ext TLE8888.IGN2: free diagnostic: Ok
2020-10-22_21_16_53_491: EngineState: ext TLE8888.IGN3: free diagnostic: Ok
2020-10-22_21_16_53_492: EngineState: ext TLE8888.IGN4: free diagnostic: Ok
2020-10-22_21_16_53_492: EngineState: Total pins count: 66
2020-10-22_21_17_03_704: EngineState: WARNING: no CAM signals

**Comment by rusefillc** [comment]
looks good to me

let's remove old commented out values like E12 since those are not helping?

**Comment by mck1117** [comment]
@rusefillc you should check this firmware on the QA test MRE setup to make sure everything does what we think it does

**Comment by rusefillc** [comment]
@mck1117 absolutely, that's exactly what I did

**Comment by dron0gus** [comment]
BTW, I have found way to control TLE8888 Main Relay output from SW. Do we need this? This will cause emun change...

**Comment by mck1117** [comment]
I think that's a good idea - for example, it would be nice to disable the main relay in case of fatal error.

**Comment by dron0gus** [comment]
Then we should think about other functions that can be exported through GPIO API. Like enabling/disabling CAN interface, IGN input, something else? And extend TLE8888 pin range to cover all future updates.

**Comment by rusefillc** [comment]
we assume that we have pin/enum mechanism so we do not have to squash all changes together, let's merge thg his stuff

draft or no draft?

**Comment by dron0gus** [comment]
Not draft now. Need to bump FLASH_DATA_VERSION.

**Comment by rusefillc** [comment]
@shadowm60 can you try master?

**Comment by shadowm60** [comment]
Yes, i'll download tomorrow the bundle and flash it, then take the car for a test drive

**Pull request merged**
