### PR TITLE
Prepare configurations for SW knock detection

### PR DESCRIPTION
**Pull request by shadowm60**
- Configurations needed for base noise
- TS usability for base noise definition

### CODE REVIEW

**Comment by shadowm60** [comment]
I've got Fail on build-primary-bundle with the following error:
    [junit] Running com.rusefi.FullServerTest
    [junit] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 62.056 sec

I have no idea what to do to make it pass.

**Comment by rusefillc** [comment]
@shadowm60 that's probably sporadic unrelated issue, running again just to try

**Comment by mck1117** [comment]
it probably actually needs a wider range - the noise floor on a disconnected sensor is down around -60dbv

**Comment by shadowm60** [comment]
I belive that in the base noise we should not consider -60 dB, but if i lt makes sens  i can change the scale.

**Comment by mck1117** [comment]
It's been a while since I looked, but I seem to remember seeing a log from @960 with a noise floor down around -35 or -40 dbv

**Pull request merged**
