### PR TITLE
Do compiler check first

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by rusefillc** [comment]
I did something similar in master already does it not work?

**Comment by dron0gus** [comment]
> I did something similar in master already does it not work?

Ups. Let me update.

**Comment by dron0gus** [comment]
cpp files are compiled after c. So gcc version is checked after all c files get compiled. That may take some time.

**Comment by rusefillc** [comment]
Can we put cpp before C?

**Comment by mck1117** [comment]
> Can we put cpp before C?

Not without changing the inner makefile bits of chibios, no.  Just use a C file.

**Comment by dron0gus** [comment]
Check is moved to first compiled c-file.

**Pull request merged**
