### PR TITLE
remove engine pointer passing

### PR DESCRIPTION
**Pull request by mck1117**
Regex replace of various PASS_ENGINE_PARAMETER_SIGNATURE and friends with empty string.

Follow on to #3551

### CODE REVIEW

**Comment by racer-coder** [comment]
hahaha I was just writing a sed script to do this

**Comment by racer-coder** [comment]
for i in " PASS_ENGINE_PARAMETER_SUFFIX" " DECLARE_CONFIG_PARAMETER_SUFFIX" DECLARE_ENGINE_PARAMETER_SIGNATURE " DECLARE_ENGINE_PARAMETER_SUFFIX" DECLARE_ENGINE_PARAMETER_SUFFIX PASS_ENGINE_PARAMETER_SIGNATURE PASS_CONFIG_PARAMETER_SIGNATURE " PASS_CONFIG_PARAMETER_SUFFIX" PASS_ENGINE_PARAMETER_SUFFIX "EXPAND_Engine;" EXPAND_Engine DECLARE_CONFIG_PARAMETER_SIGNATURE; do
        git grep -l $i | xargs sed -i "s/$i//g"
    done
    git checkout firmware/controllers/core/engine_ptr.h

**Comment by mck1117** [comment]
come back when you've implemented rusefi in sed https://github.com/shinh/sedlisp/blob/master/sedlisp.sed

**Comment by racer-coder** [comment]
Isn't that why we have Lua?

**Comment by mck1117** [comment]
come back when you've implemented rusefi in lua, then a lua interpreter in sed

**Pull request merged**
