### PR TITLE
javac builds use iso-8859-1 encoding

### PR DESCRIPTION
**Pull request by nmschulte**
```
[javac] /rusefi/rusefi/java_console/io/src/main/java/peak/can/basic/MutableTPCANHandle.java:4: error: unmappable character for encoding ASCII
[javac]  * @LastChange $Date: 2020-08-07 16:40:53 +0200 (ven., 07 août 2020) $
[javac]                                                             ^
```

### CODE REVIEW

**Comment by rusefillc** [comment]
This PR seems to focus on Ant config files while we are moving to gradle https://github.com/rusefi/rusefi/issues/3014

**Comment by nmschulte** [comment]
It seems `gradlew` still respects the `build.xml` then, as these changes resolve the problem (when using `gradlew`, via `misc/jenkins/functional_test_and_build_bundle/build_current_bundle.sh`, via e.g. `misc/jenkins/build_java_console.sh`).

Is there a different place I should do this?

**Comment by rusefillc** [comment]
No, ant and gradle output into different folder thus clean different folders

**Comment by nmschulte** [comment]
I pruned this to just the `java_console` build, which should eventually go away with #3014 (and the shell script ported to `gradlew` at the same time).

**Pull request merged**
