### PR TITLE
Launch control unit tests update

### PR DESCRIPTION
**Pull request by shadowm60**
- VSS update to have mock in case of unit tests
- launch small optimization
- condition checks added in unit tests and a basic use case.

### CODE REVIEW

**Comment by rusefillc** [comment]
@shadowm60 I have to be honest I have not reviewed the test - I just know that _any_ test is better than nothing :)

do you have more ideas for more tests or do you think it's complete?


coverage report is at https://rusefi.com/docs/unit_tests_coverage/

**Comment by rusefillc** [comment]
See https://github.com/rusefi/rusefi/issues/1973

**Comment by rusefillc** [comment]
https://rusefi.com/docs/unit_tests_coverage/ shows fresh stuff now!

See https://rusefi.com/docs/unit_tests_coverage/firmware/controllers/algo/launch_control.cpp.gcov.html

**Comment by shadowm60** [comment]
Based on the report i could still add some tests. Let me do it today and then i think it is fine.
I still want the update function to be reorganized,

**Comment by shadowm60** [comment]
@rusefillc can we close this pull request, i plan to move from thread to periodic fast callback, and in that pull request i will add the rest of the tests, this way i think it's simpler to track, if you agree with me, if not i'll continue here.

**Comment by rusefillc** [comment]
@shadowm60 this was already merged into master

**Pull request merged**
