### PR TITLE
enable LSE (via: LSE max wait patches)

### PR DESCRIPTION
**Pull request by nmschulte**
for #4556, via https://github.com/rusefi/ChibiOS/pull/23

### CODE REVIEW

**Comment by mck1117** [comment]
does this not hang on boot if you don't have an LSE?

**Comment by nmschulte** [comment]
> does this not hang on boot if you don't have an LSE?

I will test this soon on Proteus, but if I understood the issue correctly, the patches of https://github.com/rusefi/ChibiOS/pull/23 avoid the hang: exits the busy loop after 1 million tries.

**Comment by nmschulte** [comment]
Proteus F7 (no LSE):
```
I 230107 000204.137 [Commands Queue] BinaryProtocol - Sending [set date 2023-01-07T00:02:03.977]
I 230107 000204.175 [communication executor1] MessagesCentral - postMessage EngineState: confirmation_set date 2023-01-07T00:02:03.977:32
I 230107 000207.666 [Commands Queue] BinaryProtocol - Sending [get date]
I 230107 000207.780 [communication executor1] MessagesCentral - postMessage EngineState: Current RTC time: 07 Jan 2023 00:02:06
I 230107 000207.780 [communication executor1] MessagesCentral - postMessage EngineState: confirmation_get date:8
I 230107 000215.389 [Commands Queue] BinaryProtocol - Sending [get date]
I 230107 000215.494 [communication executor1] MessagesCentral - postMessage EngineState: Current RTC time: 07 Jan 2023 00:02:14
I 230107 000215.495 [communication executor1] MessagesCentral - postMessage EngineState: confirmation_get date:8
I 230107 000218.276 [Commands Queue] BinaryProtocol - Sending [get date]
I 230107 000218.398 [communication executor1] MessagesCentral - postMessage EngineState: Current RTC time: 07 Jan 2023 00:02:17
I 230107 000218.398 [communication executor1] MessagesCentral - postMessage EngineState: confirmation_get date:8
```

**Comment by rusefillc** [comment]
@mck1117 @nmschulte what's the status here? :)

**Comment by rusefillc** [comment]
@nmschulte please confirm real hardware test result.

**Comment by rusefillc** [comment]
@mi-hol FYI example of reality in terms of human coordination here

**Comment by rusefillc** [comment]
@mi-hol is this an opportunity to discuss and agree and write down common norms of following up or giving up?

**Comment by mck1117** [comment]
> @nmschulte please confirm real hardware test result.

hardware CI looked OK, so pending approval from @nmschulte , I think we're good to go?

**Comment by nmschulte** [comment]
My last round of testing went as well as my first: it seems like this works well on Proteus, and should work well on others.

**Review by mck1117 — APPROVED** [review]

**Comment by nmschulte** [comment]
I apologize if my communication was poor; my log [here](https://github.com/rusefi/rusefi/pull/4944#issuecomment-1374388983) was intended to convey the system functioning.

**Comment by mi-hol** [comment]
> @mi-hol is this an opportunity to discuss and agree and write down common norms of following up or giving up?

https://github.com/rusefi/rusefi/issues/5059

**Pull request merged**
