### PR TITLE
don't "validate instant RPM"

### PR DESCRIPTION
**Pull request by mck1117**
Not much reason to do this - we don't make this check at all for non-instant RPM, so there isn't a reason to do it for instant RPM either.  It could actually hinder starting for an engine that starts quickly - it will give a wrong RPM reading if the engine kicks before a full cycle has completed, increasing engine speed past the cranking threshold before a full cycle (and "normal" RPM reading) is complete.  The wrong RPM will cause events to be scheduled late, possibly hindering engine start, as it means ignition timing will be (possibly significantly) retarded from the set value.

### CODE REVIEW

**Comment by rusefillc** [comment]
@andreika-git do you know anything about this check?

**Comment by rusefillc** [comment]
@mck1117 how did you end up there - is this related to any other work?

**Comment by mck1117** [comment]
> @mck1117 how did you end up there

I tried changing things to *always* use instant RPM instead of ever using "normal" RPM, and ran in to this.

**Comment by rusefillc** [comment]
gotcha. let's give @andreika-git 48 hours?

**Comment by mck1117** [comment]
works for me!

**Comment by andreika-git** [comment]
> 
> 
> @andreika-git do you know anything about this check?

Yes, I remember it. The early instant RPM implementation was far less reliable than "normal RPM":
image
Here's a spike of 7279 RPM right at the start (2018-02-07, winter cold start at -12 degrees C). It was unpredictable without that check. 
The question is whether we've fixed it or not.

**Comment by rusefillc** [comment]
We're recently added second trigger gap into many triggers to better handle start and stop noises

**Comment by rusefillc** [comment]
This winter we need cold start experiments :)

**Comment by mck1117** [comment]
> This winter we need cold start experiments :)

you can recreate cold by putting in SAE 60 oil and letting your battery run down a bit 🙂

**Pull request merged**
