### PR TITLE
Add CrankShaft pin to generated_ts_name_by_pin.cpp for 48way

### PR DESCRIPTION
**Pull request by sbtoonz**

### CODE REVIEW

**Comment by rusefillc** [comment]
Does https://github.com/rusefi/rusefi/commit/b0252fd3df80ea05a006e709bb622d757fb35361 help?

**Comment by sbtoonz** [comment]
> Does [b0252fd](https://github.com/rusefi/rusefi/commit/b0252fd3df80ea05a006e709bb622d757fb35361) help?

I had saw this cpp used in Core8 and was unsure of its necessity

**Comment by sbtoonz** [comment]
[b0252fd](https://github.com/rusefi/rusefi/commit/b0252fd3df80ea05a006e709bb622d757fb35361)

based on context of this commit the generated_ts_name_by_pin.cpp should be generated automatically in build process

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/1d629df88451a4af81fc2cfafe828f0a0f4822e0

**Comment by sbtoonz** [comment]
OK I read the entire file and not the comparison snip

I see the use of this file at first in the comparison glance it looked like it was a "write if not found" action

**Pull request closed without merging**
