### PR TITLE
Sent on AlphaX 8chan

### PR DESCRIPTION
**Pull request by dron0gus**

### CODE REVIEW

**Comment by dron0gus** [comment]
```
2024-12-06_01_42_49_156: EngineState: ---- SENT input 1 ---- on 24A - Hall Input 3 / SENT
2024-12-06_01_42_49_156: EngineState: Unit time 354 CPU ticks 1.638888832 uS
2024-12-06_01_42_49_156: EngineState: Pause pulse detected No
2024-12-06_01_42_49_157: EngineState: Total pulses 1153277
2024-12-06_01_42_49_157: EngineState: Last valid fast msg Status 0x0 Sig0 0xAD8 Sig1 0x527
2024-12-06_01_42_49_157: EngineState: Restarts 0
2024-12-06_01_42_49_158: EngineState: Interval errors 1950 short, 11881 long
2024-12-06_01_42_49_158: EngineState: Total frames 107587 with CRC error 900 (0.836532288%)
2024-12-06_01_42_49_160: EngineState: Total slow channel messages 0 with crc6 errors 0 (NaN%)
2024-12-06_01_42_49_160: EngineState: Sync errors 3457
2024-12-06_01_42_49_164: EngineState: --------------------
2024-12-06_01_42_49_165: EngineState: confirmation_sentinfo:8
```

**Comment by rusefillc** [comment]
Cherry picked five commits

https://github.com/rusefi/rusefi/commit/5bd2ef46c6dfe4cfd73535874054629c1b774270 is a bit of a mess hopefully code comment helps a bit

**Comment by rusefillc** [comment]
@dron0gus unit tests were failing

I've dropped three commits and pushed https://github.com/rusefi/rusefi/commit/fbed899881c3b48783b07e203acdb063478ac885 https://github.com/rusefi/rusefi/commit/bbabc1335b94e2d55035e7455d5a1a94d73b70a3

@dron0gus please rebase and let make it green

**Comment by rusefillc** [comment]
Looks like this is now https://github.com/rusefi/rusefi/issues/7077

**Pull request merged**
